codemod/codemod

apps/docs/README.md
apps/docs/api-reference/introduction.mdx
apps/docs/api-reference/openapi.json
apps/docs/development.mdx
apps/docs/essentials/images.mdx
apps/docs/essentials/reusable-snippets.mdx
apps/docs/essentials/settings.mdx
apps/docs/introduction.mdx
apps/docs/mint.json
apps/docs/quickstart.mdx
apps/vsce/src/components/engineService.ts
apps/vsce/src/components/messageBus.ts
apps/vsce/src/components/webview/MainProvider.ts

chore: implement codemod engine node checker

---

apps/vsce/src/components/buildArguments.ts
apps/vsce/src/components/engineService.ts
apps/vsce/src/components/webview/MainProvider.ts
apps/vsce/src/utilities.ts

Fix Windows glob pattern, increase timeout

fix: fix windows glob pattern

---

apps/vsce/package.json

chore: update version

---

apps/cli/src/downloadCodemod.ts
apps/cli/src/runner.ts
apps/cli/src/utils.ts

CDMD-2527 [CLI] Improve styling of displayed message for `codemod ${name}`

---

apps/cli/src/printer.ts
apps/cli/src/utils.ts

feat: Colorful errors in console with paths (CDMD-2548)

---

apps/docs/codemod-registry/publishing-codemods.mdx
apps/docs/codemod-studio/quickstart.mdx

add publishing codemods doc

---

apps/cli/README.md

Update CLI & npm package README.md

---

apps/cli/src/executeMainThread.ts
apps/cli/src/telemetryService.ts
pnpm-lock.yaml

fix: fix cli telemetry

---

apps/cli/src/executeMainThread.ts
apps/cli/src/getTransformer.ts
apps/cli/src/telemetryService.ts
apps/cli/test/runJscodeshiftCodemod.test.ts
apps/cli/test/runTsMorphCodemod.test.ts

This PR fixes linting issues under `apps/cli` directory.
All the changes were manual changes. Some of these changes could have been fixed using biome check apply unsafe mode, but I didn't want to do it as it wouldn't make fixes to all the files.

[Biome migration][3/n][Manual changes] Fix linting issues in `apps/cli`

---

apps/vsce/src/components/downloadService.ts
apps/vsce/src/components/engineService.ts
apps/vsce/src/components/webview/WebviewResolver.ts
apps/vsce/src/extension.ts
apps/vsce/src/telemetry/vscodeTelemetry.ts
apps/vsce/test/dowloadService.test.ts
apps/vsce/webview/src/jobDiffView/App.tsx
apps/vsce/webview/src/shared/utilities/vscode.ts
apps/vsce/webview/vite.config.ts

This PR fixes linting issues under `apps/vsce` directory.
All the changes were manual changes. Some of these changes could have been fixed using biome check apply unsafe mode, but I didn't want to do it as it wouldn't make fixes to all the files.

[Biome migration][4/n][Manual changes] Fix linting issues in `apps/vsce`

---

apps/studio/src/components/ResizePanel/ResizeHandler.tsx
apps/studio/src/pageComponents/index.tsx
apps/studio/src/pageComponents/main/themeContext.tsx
apps/studio/src/store/slices/CFS/index.ts
apps/studio/src/utils/Either.ts
apps/studio/src/utils/download.ts
apps/studio/src/utils/injectCFSOutputToCodemod.ts
apps/studio/src/utils/proxy.ts
apps/studio/src/utils/webworker.ts

This PR fixes linting issues under `apps/studio` directory.
All the changes were manual changes. Some of these changes could have been fixed using biome check apply unsafe mode, but I didn't want to do it as it wouldn't make fixes to all the files.

[Biome migration][5/n][Manual changes] Fix linting issues in `apps/studio`

---

apps/studio/src/hooks/useTreeNode.ts
apps/studio/src/store/slices/codemodOutput.ts
apps/studio/src/store/slices/mod.ts
apps/studio/src/store/slices/snippets.ts
apps/studio/src/utils/babelParser/index.ts
pnpm-lock.yaml

fix: fix ts issue

---

.vscode/settings.json
apps/cli/src/buildOptions.ts
apps/cli/src/executeMainThread.ts
apps/cli/src/handleListCliCommand.ts
apps/cli/src/messages.ts
apps/vsce/src/components/engineService.ts
biome.json
pnpm-lock.yaml

fix: fix vsce empty registry

---

apps/registry/codemods/react/remove-forward-ref/README.md
apps/registry/codemods/react/remove-forward-ref/config.json
apps/registry/codemods/react/remove-forward-ref/index.d.ts
apps/registry/codemods/react/remove-forward-ref/package.json
apps/registry/codemods/react/remove-forward-ref/src/index.ts
apps/registry/codemods/react/remove-forward-ref/test/test.ts
apps/registry/codemods/react/remove-forward-ref/tsconfig.json
pnpm-lock.yaml

adds new codemod for removing forwardRef function

feat: add react/remove-forward-ref codemod

---

apps/cli/package.json
apps/vsce/package.json

update versions of vsce and cli

chore: update versions

---

apps/cli/src/fileDownloadService.ts
apps/cli/src/runCodemod.ts

CDMD-2625 [CLI] Show file names rather than S3 URLs when running a codemod + improve styling/message

---

apps/cli/src/executeMainThread.ts

CDMD-2626 [CLI] Remove dummy prefix text in codemod --help

---

apps/studio/src/pageComponents/index.tsx

bug fix
mobile view currently is broken and folks dont see the video.
users should be able to see the video now. 
https://mintlify.s3-us-west-1.amazonaws.com/codemodcom/images/codemod-studio/codemod-studio-quickstart.mp4

[Studio] fix: update the video link for mobile view - CDMD-2632

---

apps/docs/mint.json

This PR adds redirects from the old blog URLs to their counterparts on the docusaurus instance on [blog.codemod.com](blog.codemod.com).

Docs to blog redirects

---

apps/vsce/webview/src/codemodList/App.tsx

[VSCE] fix: missing spaces in text - CDMD-2700

---

apps/cli/src/executeMainThread.ts

Reverts codemod-com/codemod#114

Revert "[VSCE, CLI] fix: `--json` option is not applied to command list - CDMD-2702"

---

apps/vsce/src/extension.ts
apps/vsce/webview/src/codemodList/App.tsx

[VSCE] fix: Multiple View Registration Errors - CDMD-2701

---

apps/vsce/src/extension.ts

Reverts codemod-com/codemod#113

Revert "[VSCE] fix: Multiple View Registration Errors - CDMD-2701"

---

apps/backend/prisma/schema.prisma
apps/backend/prisma/seed.ts
apps/backend/src/schemata/query.ts
apps/backend/src/server.ts
apps/studio-backend/prisma/migrations/20240308115430_add_codemod_versions/migration.sql

- splitted one codemod table into two separate tables
- updated seeder script
- updated endpoints
- added pagination to codemods endpoint
- added including versions to codemods/:slug endpoint

[Registry]: Distribute codemod data (CDMD-2733)

---

apps/studio/package.json
pnpm-lock.yaml

https://github.com/clerk/javascript/pull/2665

[Studio] fix: clerk/themes build fix

---

apps/backend/Dockerfile

[Backend]: Deploy backend (CDMD-2743)

---

apps/backend/Dockerfile

[Backend]: fixed Dockerfile (CDMD-2763)

---

apps/backend/prisma/schema.prisma

Added binary target for Prisma schema for correct database querying.

[Backernd]: Fixed `schema.prisma` for correct deployment (CDMD-2763)

---

.github/workflows/ci-cd.yml
package.json

Created first step of CI/CD which is building tagging and pushing our docker image to AWS ECR based on version of our backend app.

[CI/CD]: Created first stage of CI/CD process (CDMD-2742)

---

.github/workflows/ci-cd.yml
apps/backend/package.json

Created CI/CD process for backend app.

[CI/CD] Crearte CI/CD process for backend (CDMD-2742)

---

apps/docs/codemod-registry/publishing-codemods.mdx
apps/docs/external-links/codemod-registry.mdx
apps/docs/external-links/codemod-studio.mdx
apps/docs/external-links/vsce.mdx
apps/docs/mint.json

- relocate sidebar external links

Docs improvements

---

apps/backend/package.json
apps/backend/src/server.ts

- Created endpoint for checking current version of backend
- Bumped version to 0.0.37

[Backend]: Added endpoint for checking version of backend.

---

apps/studio/src/pageComponents/main/5PaneSetup.tsx
apps/studio/tailwind.config.ts

Improves the Debug panel by allowing it to scroll vertically
Debug panel can't be scrolled vertically when the content grows outside the initial viewpoint
User can scroll the Debug panel only if the content grows out of the initial viewpoint
-   **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

Make Debug tab scrollable

---

.github/workflows/ci-cd.yml

Looks like strategy with using env variables as image version not working correctly. So we gonna update docker-compose file each time with new version of backend.

[CI/CD]: Changed logic of pulling latest docker image version.

---

apps/backend/package.json
apps/backend/prisma/migrations/20240321123931_add_description_usecasecategory_tags_engine_applicability_to_codemods_table/migration.sql
apps/backend/prisma/schema.prisma
apps/backend/prisma/seed.ts
apps/backend/src/publishHandler.ts
apps/backend/src/schemata/query.ts
apps/backend/src/server.ts

- Updated Prisma schema and added `engine`, `shortDescription`, `tags`, `useCaseCategory` for searching optimization.
- Created searching and filters logic for codemods.
- Updated `publishHandler` so `Codemod` fields will by in sync with `CodemodVersion` fields.
- Updated seeder script with seeding `engine`, `shortDescription`, `tags`, `useCaseCategory` fields.

[Backend, Registry]: Created basic searching and filters for `Codemods`. (CDMD-2729)

---

apps/studio/src/pageComponents/main/JSCodeshiftRender.tsx

-   **What kind of change does this PR introduce?** Bug fix
-   **Does this PR introduce a breaking change?** (What changes might users need to make in …

fixed behaviour on after panel hide

---

apps/backend/package.json
apps/backend/prisma/migrations/20240321170952_add_description_usecasecategory_tags_engine_applicability_to_codemods_table/migration.sql
apps/backend/prisma/schema.prisma

[Backend] chore: created a new migration & bumped version to 0.0.45

---

apps/studio/src/store/slices/CFS/prompts.ts

This PR updates the prompt used by ModGPT to eliminate common execution errors and reduce common syntax/type errors in the generated codemod.
-   **What is the current behavior?** (You can also link to an open …

Update ModGPT prompt

---

apps/backend/package.json
apps/backend/src/server.ts

- Created counters for each filter
- Bumped version to 0.0.46

[Backend, Registry]: Created counters for filters for `WebRegistry` (CDMD-2953)

---

apps/backend/package.json
apps/backend/src/server.ts

- Added last `CodemodVersion` entity to /codemods endpoint
- Bumped version to 0.0.48

[Backend, Registry] chore: Added last `CodemodVersion` entity to /codemods endpoint

---

apps/studio/package.json
apps/vsce/package.json
pnpm-lock.yaml

[Studio, VSCE] chore/update @svgr/webpack and webpack

---

apps/backend/package.json
apps/backend/src/schemata/query.ts
apps/backend/src/server.ts

- Updated query-string schema for category and author
- Updated filter strategy for category and author
- Bumped version 0.0.49

[Backend, Registry]: Added multiple filters on `category` and `author` (CDMD-3009)

---

apps/backend/package.json
apps/backend/prisma/migrations/20240326165332_added_arguments_field/migration.sql
apps/backend/prisma/schema.prisma
apps/backend/src/db/prisma.ts
apps/backend/src/publishHandler.ts
apps/backend/src/server.ts

- Generated migrations.
- Populated `Codemod` and `CodemodVersion` schemas with `arguments` field.
- Generated types.
- Changed `/publish` endpoint
- Bumped version to 0.0.52

[Backend, Registry]: Added arguments field to `Codemod` models and modified `/list` endpoint. (CDMD-3019)

---

apps/studio/src/components/Panel/PanelHeader.tsx
apps/studio/src/components/Panel/panel.css
apps/studio/src/icons/VisibilityIcon.tsx
apps/studio/src/pageComponents/main/Layout.tsx
apps/studio/src/pageComponents/main/bottom-panel/PageBottomPane.tsx
apps/studio/src/pageComponents/main/bottom-panel/side-components.tsx
apps/studio/src/pageComponents/main/bottom-panel/types.ts

- Fix
- https://linear.app/codemod/issue/CDMD-2962/bottom-pane-fix-styling

bottom pane styling improvements

---

apps/vsce/src/components/buildArguments.ts
apps/vsce/src/components/engineService.ts

- get codemod list from the api
- fix dry run args

[VSCE] fix: fix dry run

---

apps/studio/src/components/Snippet/configure.ts

[Studio] fix: fix ts target

---

apps/vsce/src/codemods/types.ts
apps/vsce/src/components/engineService.ts
apps/vsce/src/selectors/selectCodemodTree.ts
apps/vsce/webview/src/codemodList/CodemodNodeRenderer/Codemod.tsx

[VSCE] fix: support arguments

---

apps/studio/package.json
apps/studio/src/utils/proxy.test.ts
pnpm-lock.yaml

Removes dependencies that remain from CRA and other unused packages

[Studio] chore: remove CRA artifacts

---

apps/studio/package.json
apps/vsce/webview/package.json
pnpm-lock.yaml

chore: update katex, remove webpack

---

apps/studio/src/store/slices/snippets.ts

fix: fix build crash

---

apps/backend/package.json
apps/backend/src/handlers/getCodemodsHandler.ts
apps/backend/src/schemata/query.ts
apps/backend/src/services/codemodService.ts

- Added `featured` filter to the codemod search.
- Bumped version to 0.0.56

[Backend, Registry]: Added `featured` filter to the codemod search. (CDMD-3074)

---

.vscode/settings.json
packages/codemods/react/19/replace-act-import/.codemodrc.json
packages/codemods/react/19/replace-act-import/README.md
packages/codemods/react/19/replace-act-import/__testfixtures__/fixture1.input.js
packages/codemods/react/19/replace-act-import/__testfixtures__/fixture1.output.js
packages/codemods/react/19/replace-act-import/__testfixtures__/fixture2.input.js
packages/codemods/react/19/replace-act-import/__testfixtures__/fixture2.output.js
packages/codemods/react/19/replace-act-import/__testfixtures__/fixture3.input.js
packages/codemods/react/19/replace-act-import/__testfixtures__/fixture3.output.js
packages/codemods/react/19/replace-act-import/__testfixtures__/fixture4.input.js
packages/codemods/react/19/replace-act-import/__testfixtures__/fixture4.output.js
packages/codemods/react/19/replace-act-import/__testfixtures__/fixture5.input.js
packages/codemods/react/19/replace-act-import/__testfixtures__/fixture5.output.js
packages/codemods/react/19/replace-act-import/__testfixtures__/fixture6.input.js
packages/codemods/react/19/replace-act-import/__testfixtures__/fixture6.output.js
packages/codemods/react/19/replace-act-import/package.json
packages/codemods/react/19/replace-act-import/src/index.ts
packages/codemods/react/19/replace-act-import/test/test.ts
packages/codemods/react/19/replace-act-import/tsconfig.json
pnpm-lock.yaml

- Adds react v19 codemod to replace react-dom/test-utils `act()` method usage to be imported from `react`

feat: adds react v19 act() method codemod

---

apps/cli/src/downloadCodemod.ts
apps/cli/src/executeMainThread.ts
apps/cli/src/handleInstallDependencies.ts
apps/cli/src/handleLoginCliCommand.ts
apps/cli/src/handlePublishCliCommand.ts
apps/cli/src/printer.ts
apps/cli/src/runAstgrepCodemod.ts
apps/cli/src/utils.ts

- try to build if no build file detected
- better error messaging with logical branching
- add loader messages (and ability to use multiple loaders in the same message with neat callback signature)
- add clearer name notification upon publishing (using `name` from `.codemodrc.json`)

feat: fallback build, loader messages, notifications (CDMD-2958, CDMD-3081)

---

apps/backend/package.json
apps/backend/prisma/migrations/20240405180019_s3_data_format/migration.sql
apps/backend/prisma/schema.prisma
apps/backend/prisma/seed.ts
apps/backend/src/customHandler.ts
apps/backend/src/handlers/getCodemodDownloadLink.ts
apps/backend/src/handlers/getCodemodsListHandler.ts
apps/backend/src/handlers/revokeTokenHandler.ts
apps/backend/src/handlers/validationHandler.ts
apps/backend/src/publishHandler.test.ts
apps/backend/src/publishHandler.ts
apps/backend/src/server.ts
apps/backend/src/services/codemodService.ts
apps/cli/package.json
apps/cli/src/apis.ts
apps/cli/src/downloadCodemod.ts
apps/cli/src/handleInitCliCommand.ts
apps/cli/src/handleLoginCliCommand.ts
apps/cli/src/handlePublishCliCommand.ts
apps/cli/src/handleWhoAmICommand.ts
apps/cli/src/utils.ts
packages/utilities/src/index.ts
packages/utilities/src/schemata/codemodListResponse.ts
packages/utilities/src/schemata/validateTokenResponse.ts
pnpm-lock.yaml

- Introduces concept of organizations into our authentication strategy and token validation endpoints.
- Improves whoami command to show user organization slugs he has access to and can publish under.
- Mostly adds changes to update how our CLI works with backend that now understands organizations

[Backend, CLI] feat: initial orgs work (CDMD-2663, CDMD-2664)

---

package.json
pnpm-lock.yaml

chore(deps-dev): bump vitest from 1.0.1 to 1.4.0

---

apps/backend/src/schemata/schema.ts
apps/backend/src/server.ts
apps/backend/src/services/GithubProvider.ts
apps/backend/src/services/SourceControl.ts

[Backend] add endpoint for getting the list of user repositories

---

apps/docs/building-codemods/codemod-studio.mdx
apps/docs/deploying-codemods/introduction.mdx

Fixes occurrences of using 'deploy' instead of 'run' codemods.

fix deploy occurrences

---

packages/codemods/react-router/4/replace-param-prop/src/index.ts
packages/codemods/react-router/4/replace-param-prop/test/test.ts

Fixes FN where codemod not replacing params in  mapStateToProps and mapDispatchToProps
-   **What is the new behavior (if this is …

chore: [Codemod:FN] replace-params not replacing params in mapStateToProps and mapDispatchToProps

---

apps/backend/src/server.ts
packages/filemod/package.json
packages/filemod/src/filemod.ts
packages/filemod/src/unifiedFileSystem.test.ts
packages/filemod/src/unifiedFileSystem.ts

- adds moveFile API method
- adds checks for removed files/dirs for readDirectory method

[Filemod]: add ability to move files

---

apps/backend/package.json
apps/backend/src/services/codemodService.ts

[Backend, Registry]: Fix codemods search

---

apps/backend/package.json
apps/backend/src/services/codemodService.ts

- Fixed usecasecategory and framework fields
- Bumped version to 0.0.72

[Backend, Registrry]: Fixed usecasecategory and framework fields

---

apps/backend/package.json
apps/backend/src/services/codemodService.ts

- add slug to `codemods/list` endpoint.
- bumped version to 0.0.73

[Backend, Registry]: Added slug field to `codemods/list` endpoint

---

apps/cli/package.json
apps/cli/src/buildCodemodOptions.ts
apps/cli/src/downloadCodemod.ts
apps/cli/src/messages.ts
apps/cli/src/printer.ts
apps/cli/src/runCodemod.ts
apps/cli/src/runner.ts

- allows running recipes from local machine
- allows using local paths to specify path to the codemod in `names` field

[CLI] feat: allow running recipes (CDMD-3117)

---

apps/backend/package.json
apps/backend/src/services/codemodService.ts

- renamed filter names
- bumped version to 0.0.74

[Backend, Registry] Renamed filters names

---

apps/studio/package.json
apps/studio/src/auth/SignIn.tsx
apps/studio/src/components/ui/progress.tsx
apps/studio/src/pageComponents/main/5PaneSetup.tsx
pnpm-lock.yaml

[Studio] implement codemod run progress bar - CDMD-3092

---

apps/docs/building-codemods/getting-started.mdx
apps/docs/introduction.mdx
apps/docs/mint.json
package.json

This PR updates docs and fixes issues related to the new website migration.

[docs] new website migration docs fixes

---

apps/backend/package.json
apps/backend/src/services/codemodService.ts

- Rewrote incorrect database queries that were causing connection pool overflow.
- Bumped version to 0.0.79

[Backend]: Removed unoptimized queries to database.

---

package.json

[Monorepo]: updated package manager

---

apps/backend/package.json
apps/backend/src/services/codemodService.ts

- fixed types
- bumped version to 0.0.80

[Backend]: Fixed types for `codemods/list`

---

packages/codemods/eslint/biome/migrate-rules/src/functions.ts

fix: fix biome test

---

packages/codemods/eslint/biome/migrate-rules/src/functions.ts

fix: fix biome test (#365)

---

apps/cli/README.md
apps/cli/package.json

This PR adds our github repo link to the cli package.

[cli] Update package.json

---

apps/backend/package.json
apps/backend/src/services/codemodService.ts
package.json
packages/utilities/src/schemata/codemodListResponse.ts

- added updatedAt field to the `codemods/list` endpoint
- added `useCaseCategory` and `framework` field to the `codemods/:slug` endpoint
- added sorting to codemod versions to `codemods/:slug` endpoint
- fixed doubling dependencies 
- bumped version to 0.0.82

[Backend]: Fixed some responses related to frontend work.

---

apps/docs/mint.json

Adds link to website home in docs nav logo.

[docs] add home link in docs nav

---

apps/vsce/package.json
apps/vsce/src/components/engineService.ts
apps/vsce/src/constants.ts
apps/vsce/src/extension.ts
apps/vsce/webview/src/CodemodEngineNodeNotFound/index.tsx
apps/vsce/webview/src/main/App.tsx
pnpm-lock.yaml

[VSCE] remove codemod package dependency and use globally installed CLI - CDMD-3174, CDMD-3176

---

apps/frontend/app/(website)/studio/README.md

Updates Codemod Studio README file.

[studio] Update README.md

---

.github/ISSUE_TEMPLATE/request-codemod.md

[chore] [issue template] updated the codemod template

---

apps/frontend/app/(website)/page.tsx
apps/frontend/app/(website)/studio/main/5PaneSetup.tsx
apps/frontend/app/(website)/studio/main/Header.tsx
apps/frontend/app/(website)/studio/page.tsx
apps/frontend/app/(website)/studio/src/components/Snippet/Monaco.tsx
apps/frontend/app/(website)/studio/src/components/Snippet/MonacoDiffEditor.tsx
apps/frontend/app/(website)/studio/src/components/chatbot/ChatMessage.tsx
apps/frontend/app/(website)/studio/src/components/chatbot/CodeBlock.tsx
apps/frontend/app/(website)/studio/src/components/chatbot/ModelSelector.tsx
apps/frontend/app/context/index.ts
apps/frontend/app/context/useTheme.tsx
apps/frontend/app/layout.tsx
apps/frontend/components/global/Footer/index.tsx
apps/frontend/hooks/useTheme.tsx
apps/frontend/middleware.ts
apps/frontend/tailwind.config.ts
packages/codemods/react/19/remove-context-provider/README.md
packages/codemods/react/19/use-context-hook/README.md

uncomment middleware

---

apps/frontend/components/templates/AboutPage/AboutPageContent.tsx
apps/frontend/components/templates/Registry/FilterSection.tsx

- About page team member pre company logos → breaking out of constraints
- Registry Filter Buttons on Dark mode

[web app] style bugs reported by tinloof - CDMD-3177

---

apps/frontend/app/(website)/studio/src/components/chatbot/ChatPanel.tsx
apps/frontend/app/(website)/studio/src/store/zustand/CFS/alias.ts

bug fix
fixed that with @DmytroHryshyn 
-   **Does this PR …

Fixed error prompt

---

apps/frontend/components/shared/pt.blocks/Collapsible/index.tsx

[Web app] Fix inconsistent chevron size - CDMD-3184

---

apps/frontend/app/(website)/studio/page.tsx
apps/frontend/app/(website)/studio/src/components/Panel/panel.css
apps/frontend/app/(website)/studio/src/components/button/button.css
apps/frontend/app/(website)/studio/src/studio.css
apps/frontend/app/(website)/studio/tailwind.config.ts
apps/frontend/app/auth/AuthButtons.tsx
apps/frontend/app/layout.tsx
apps/frontend/components/global/Navigation/DesktopNavigation.tsx
apps/frontend/components/templates/Registry/DesktopFilters.tsx
apps/frontend/hooks/useTheme.tsx
apps/frontend/styles/globals.css
apps/frontend/tailwind.config.ts

Theme fixes

---

apps/frontend/app/auth/AuthButtons.tsx

avatar icon fix

---

apps/frontend/app/(website)/studio/main/DownloadZip.tsx
apps/frontend/app/(website)/studio/tailwind.config.ts
apps/frontend/styles/globals.css
apps/frontend/tailwind.config.ts

layer fixes

---

apps/cli/README.md
apps/cli/src/commands/learn.ts
apps/cli/src/commands/login.ts
apps/docs/building-codemods/codemod-studio.mdx
apps/docs/external-links/codemod-studio.mdx
apps/docs/introduction.mdx
apps/frontend/app/(website)/studio/README.md
apps/frontend/app/(website)/studio/src/constants/urls.ts
apps/frontend/app/(website)/studio/src/middleware.ts
apps/frontend/components/global/Navigation/LogoWithContextMenu.tsx
apps/frontend/middleware.ts
apps/vsce/src/components/webview/CustomPanelProvider.ts
apps/vsce/src/components/webview/MainProvider.ts
apps/vsce/src/extension.ts
packages/codemods/intuita/migrate-codemod-registry/src/index.ts
packages/utilities/src/constants.ts
packages/utilities/src/index.ts

- replaces old codemod.studio URLs

replace codemod.studio with codemod.com/studio

---

apps/frontend/components/shared/RichText.tsx
apps/frontend/components/shared/pt.blocks/Collapsible/index.tsx

- https://linear.app/codemod/issue/CDMD-3180/collapsible-text-alignment-should-be-top-left
- https://linear.app/codemod/issue/CDMD-3182/add-margin-to-admonition-component
- https://linear.app/codemod/issue/CDMD-3183/same-thing-with-the-table-element-benny

[web app] style bug fixes CDMD-3180, CDMD-3182, CDMD-3183

---

apps/vsce/package.json

upd version

---

.vscode/settings.json
apps/cli/package.json
apps/cli/src/executeMainThread.ts

fix version cmd

---

apps/backend/package.json
apps/backend/src/publishHandler.test.ts
apps/backend/src/schemata/env.ts
apps/backend/src/schemata/schema.ts
apps/backend/src/server.ts
pnpm-lock.yaml

- Created `/codemodRun` endpoint for start codemod
- Created `/codemodRun/status/:jobId` for getting status of running codemod
- Bumped version to 0.0.90

[Backend]: Created necessary endpoints for `codemod-runner`

---

apps/frontend/app/(website)/blog/tag/[tag]/page.tsx
apps/task-manager/.gitignore
apps/task-manager/esbuild.config.js
apps/task-manager/package.json
apps/task-manager/reset.d.ts
apps/task-manager/src/schemata/env.ts
apps/task-manager/src/services/Auth.ts
apps/task-manager/src/services/GithubProvider.ts
apps/task-manager/src/services/SourceControl.ts
apps/task-manager/src/util.ts
apps/task-manager/src/worker.ts
apps/task-manager/tsconfig.json
pnpm-lock.yaml

Implemented basic instance for running codemods on backend using queue. It can run built codemod for provided repo, apply changes and create a pull request and check the status of codemod run.

[Backend, Codemod runner]: Created basic `codemod` runner task-manager

---

packages/codemods/react-native/74/migrate-to-fire-interval-seconds/.codemodrc.json
packages/codemods/react-native/74/migrate-to-fire-interval-seconds/LICENSE
packages/codemods/react-native/74/migrate-to-fire-interval-seconds/README.md
packages/codemods/react-native/74/migrate-to-fire-interval-seconds/package.json
packages/codemods/react-native/74/migrate-to-fire-interval-seconds/src/index.ts
packages/codemods/react-native/74/migrate-to-fire-interval-seconds/test/test.ts
packages/codemods/react-native/74/migrate-to-fire-interval-seconds/tsconfig.json
packages/codemods/react-native/74/remove-alert-action/.codemodrc.json
packages/codemods/react-native/74/remove-alert-action/LICENSE
packages/codemods/react-native/74/remove-alert-action/README.md
packages/codemods/react-native/74/remove-alert-action/package.json
packages/codemods/react-native/74/remove-alert-action/src/index.ts
packages/codemods/react-native/74/remove-alert-action/test/test.ts
packages/codemods/react-native/74/remove-alert-action/tsconfig.json
packages/codemods/react-native/74/remove-event-listener-callback/.codemodrc.json
packages/codemods/react-native/74/remove-event-listener-callback/LICENSE
packages/codemods/react-native/74/remove-event-listener-callback/README.md
packages/codemods/react-native/74/remove-event-listener-callback/package.json
packages/codemods/react-native/74/remove-event-listener-callback/src/index.ts
packages/codemods/react-native/74/remove-event-listener-callback/test/test.ts
packages/codemods/react-native/74/remove-event-listener-callback/tsconfig.json
pnpm-lock.yaml

React native 0.74 codemods

---

apps/backend/package.json
apps/backend/src/server.ts
apps/frontend/app/(website)/blog/tag/[tag]/page.tsx

- added error handling
- bumped version to 0.0.91

[Backend]: Added error handling to the codemod run functionality

---

apps/vsce/src/components/engineService.ts
apps/vsce/src/selectors/selectMainWebviewViewProps.ts

- [VSCE] Show codemods even if a workplaces is not selected
- [VSCE] Fetch codemods immediately after latest version of codemod CLI is detected

[VSCE] 2 bug fixes - CDMD-3171, CDMD-3215

---

.all-contributorsrc
apps/docs/more-resources/changelog.mdx

Adds release v1.0.3 to changelog.

[docs] Update changelog.mdx

---

packages/codemods/react-native/74/migrate-to-fire-interval-seconds/.codemodrc.json
packages/codemods/react-native/74/remove-alert-action/.codemodrc.json
packages/codemods/react-native/74/remove-event-listener-callback/.codemodrc.json

Added repo url to react-native codemods

---

apps/frontend/app/(website)/studio/main/Codemod.tsx

output update fix

---

apps/frontend/components/templates/CodemodPage/CodemodPageUI.tsx
apps/frontend/components/templates/Registry/RegistryCard.tsx
apps/frontend/components/templates/Registry/RegistrySectionCard.tsx
apps/frontend/components/templates/Registry/helpers.ts
apps/frontend/data/sanity/resolveSanityRouteMetadata.tsx
apps/frontend/types/object.types.ts
biome.json

[Frontend] feat: support frameworks property

---

apps/frontend/app/(website)/studio/main/5PaneSetup.tsx
apps/frontend/app/(website)/studio/src/store/getInitialState.ts
apps/frontend/app/(website)/studio/src/utils/openLink.ts
apps/frontend/constants/index.ts

for PR https://github.com/codemod-com/codemod/pull/460

address comments for PR #460

---

apps/frontend/app/(website)/studio/main/JSCodeshiftRender.tsx

codemod run on codemod update

---

apps/vsce/package.json

[VSCE] Bump version to 0.38.26

---

apps/frontend/components/shared/Button.tsx
apps/frontend/components/shared/RunCTAButton.tsx
apps/frontend/components/templates/CodemodPage/CodemodPageUI.tsx
apps/frontend/public/icons/cursor-ide.svg
constants.ts

[Web app] feature: Run in Cursor

---

apps/cli/package.json
apps/cli/src/fileDownloadService.ts

fix: fix cache

---

apps/frontend/app/(website)/studio/main/JSCodeshiftRender.tsx

useCodemodOutputUpdate as a separate hook

---

apps/backend/package.json
apps/backend/src/services/codemodService.ts

- added framework version tag
- bumped version to 0.0.94

[Backend]: added framework version tag

---

apps/backend/package.json
apps/backend/src/server.ts

[BACKEND] allow access from preview

---

apps/frontend/components/global/Footer/ThemeSwitcher.tsx

redundant-state-removed

---

apps/backend/package.json
apps/backend/src/schemata/schema.ts
apps/backend/src/server.ts
apps/task-manager/src/jobs/runCodemod.ts
apps/task-manager/src/services/CodemodRunner.ts
apps/task-manager/src/services/GithubProvider.ts
apps/task-manager/src/services/Redis.ts

- fixed repo cloning with token
- fixed creating branch
- changed codemod progress schema
- added branch handling

[Backend, Task-manager]: Fixes and updates for `backend` & `task-manager`

---

apps/task-manager/package.json
apps/task-manager/src/services/CodemodRunner.ts

- fixed methods because of losing `this`

[Task manager]: Changed methods in codemod runner service into arrow functions.

---

apps/frontend/app/(website)/studio/src/components/chatbot/CodeBlock.tsx

[Studio] Implement button for copying code to Codemod Panel - CDMD-3219

---

apps/docs/deploying-codemods/cli.mdx

- update help and version command placement
- update -s option phrasing

[Docs] Improve CLI docs

---

packages/runner/src/runCodemod.ts
packages/utilities/src/functions/node.ts
packages/utilities/src/index.ts

[CLI] fix: hanging when no files found (CDMD-3318)

---

packages/codemods/msw/2/upgrade-recipe/.codemodrc.json
packages/codemods/msw/2/upgrade-recipe/README.md

This PR updates MSW upgrade recipe metadata and readme.

[registry] update msw upgrade recipe readme

---

apps/cli/package.json
packages/runner/package.json
packages/runner/src/schemata/flowSettingsSchema.ts

- exclude d.ts files by default

fix: exclude d.ts by default

---

apps/frontend/app/(website)/studio/main/index.tsx

This PR fixes a regression mobile video URL after monorepo merge.

[studio] fix mobile video url regression

---

apps/task-manager/src/services/GithubProvider.ts

[Codmod-Runner] fixed base branch logic

---

.github/workflows/codemod-backend-ci-cd.yml
apps/backend/package.json

[ci/cd] chore: workflow fix

---

.github/workflows/codemod-backend-ci-cd.yml

[ci/cd] fix

---

apps/backend/package.json
apps/backend/src/services/PostHogService.ts
apps/backend/src/services/codemodService.ts

[backedn]: fixed posthog service

---

apps/cli/package.json
apps/cli/src/commands/run.ts
apps/cli/src/executeMainThread.ts

- only check file versioning if not dry run
- timeout npm view output in case of bad or no internet connection

[CLI] fix: fix new experiences

---

apps/backend/package.json
apps/backend/src/services/codemodService.ts

removed posthog service from codemodService

---

packages/utilities/src/package-boilerplate.ts

fix boilerplate

---

apps/frontend/app/(website)/studio/src/components/CodemodButton/CodemodButton.tsx
apps/frontend/app/(website)/studio/src/components/CodemodButton/Dropdown.tsx
apps/frontend/app/(website)/studio/src/components/CodemodButton/RepositoryModal.tsx
apps/frontend/app/(website)/studio/src/components/CodemodButton/hooks/useBranchLogic.ts
apps/frontend/app/(website)/studio/src/components/CodemodButton/hooks/useCodemodStatusToast.tsx
apps/frontend/app/(website)/studio/src/hooks/useCodemodExecution.ts

- Add fetching spinner for branch
- Fix styles
- Fix exec status not being rendered in CodemodButton

[studio] fix styles and logic

---

apps/backend/package.json
apps/backend/prisma/migrations/20240516114045_created_total_runs_field/migration.sql
apps/backend/prisma/schema.prisma
apps/backend/src/cron.ts
apps/backend/src/services/PostHogService.ts
apps/backend/src/services/codemodService.ts

- created migration for adding totalRuns field
- created 1 hour cronjob
- updated version to 0.0.107

[Backend]: Created 1 hour cronjob for updating totalRuns field (CDMD-3365)

---

apps/frontend/app/(website)/studio/src/components/CodemodButton/hooks/useHandleCodemodRun.ts
apps/frontend/app/(website)/studio/src/utils/transpileTs.ts
pnpm-lock.yaml

transpile ts

---

apps/frontend/app/(website)/studio/main/PaneLayout/tabsData.tsx

Fix debugger

---

apps/backend/src/publishHandler.ts
apps/backend/src/unpublishHandler.ts
apps/frontend/components/global/Navigation/LogoWithContextMenu.tsx
apps/frontend/components/templates/CodemodPage/mockData.ts
apps/frontend/components/templates/Registry/VerifiedBadge.tsx

This PR fixes minor typos in the website and web registry.

[website] fix minor typos

---

apps/task-manager/package.json
apps/task-manager/src/services/CodemodRunner.ts

[runner] fix: fixed empty 'executing codemod' status

---

packages/codemods/react/19/replace-reactdom-render/.codemodrc.json
packages/codemods/react/19/replace-reactdom-render/README.md

fix: fix react/19/replace-reactdom-render codemod description

---

apps/frontend/app/(website)/studio/main/modGPT/config.ts
apps/modgpt/src/routes/index.ts

remove second register, fix path

---

apps/vsce/webview/src/main/App.tsx

[vsce] remove all panels and display codemod list only - CDMD-3409

---

apps/vsce/src/components/buildArguments.ts
apps/vsce/webview/src/codemodList/CodemodNodeRenderer/index.tsx

[vsce] remove dry run - CDMD-3410

---

apps/modgpt/src/routes/index.ts
apps/modgpt/src/routes/sendChat.ts
apps/modgpt/src/schemata/schema.ts

another tryout

---

apps/cli/src/commands/run.ts
apps/cli/src/safeArgumentRecord.ts

[CLI] feat: printing used args (CDMD-3416)

---

apps/cli/src/downloadCodemod.ts

[CLI] feat: ask if user wants to run all the recipe codemods (CDMD-3415)

---

packages/codemods/vue/3/render-function-api/.codemodrc.json
packages/codemods/vue/3/render-function-api/.gitignore
packages/codemods/vue/3/render-function-api/LICENSE
packages/codemods/vue/3/render-function-api/README.md
packages/codemods/vue/3/render-function-api/__testfixtures__/fixture1.input.ts
packages/codemods/vue/3/render-function-api/__testfixtures__/fixture1.output.ts
packages/codemods/vue/3/render-function-api/package.json
packages/codemods/vue/3/render-function-api/src/index.ts
packages/codemods/vue/3/render-function-api/test/test.ts
packages/codemods/vue/3/render-function-api/tsconfig.json
packages/codemods/vue/3/render-function-api/vitest.config.ts
pnpm-lock.yaml

Adds a codemod for Render Function API changes in Vue 3 as described in #654.

[codemod request] Vue 3: add render api changes

---

apps/frontend/app/(website)/studio/main/modGPT/config.ts
apps/frontend/app/(website)/studio/main/modGPT/useAiService/useAiService.ts
apps/frontend/config.ts
apps/frontend/utils/strings/index.ts

codemodAI communication

---

apps/backend/package.json
apps/backend/src/server.ts
apps/backend/src/services/codemodService.ts
apps/cli/src/apis.ts
apps/cli/src/buildOptions.ts
apps/cli/src/commands/run.ts
apps/cli/src/downloadCodemod.ts
apps/cli/src/executeMainThread.ts
apps/cli/src/fileDownloadService.ts
apps/docs/deploying-codemods/cli.mdx
apps/task-manager/src/services/CodemodRunner.ts
packages/runner/src/index.ts
packages/runner/src/runCodemod.ts
packages/runner/src/schemata/flowSettingsSchema.ts
packages/utilities/src/index.ts
packages/utilities/src/schemata/apiResponses.ts
pnpm-lock.yaml

- add run summary:
- add check for version (update backend endpoint and CLI logic)
- fix `no-cache` being broken due to internal `yargs` logic
- replace `skip-install` with `no-install`

[CLI] feat: run summary, newest codemod version check (CDMD-3417, CDMD-3439, CDMD-3440)

---

apps/modgpt/src/routes/index.ts

isDevelopment removal

---

apps/frontend/styles/customizeClerkComponents.css
apps/frontend/styles/globals.css

[frontend] fix text not visible in account portal in homepage

---

packages/codemods/vue/3/render-function-api/.codemodrc.json
packages/codemods/vue/3/render-function-api/src/index.ts

[Registry]: vue/3/render-function-api

---

apps/modgpt/esbuild.config.js

minified: false

---

biome.json
packages/codemods/nuxt/4/shallow-data-reactivity/.codemodrc.json
packages/codemods/nuxt/4/shallow-data-reactivity/.gitignore
packages/codemods/nuxt/4/shallow-data-reactivity/LICENSE
packages/codemods/nuxt/4/shallow-data-reactivity/README.md
packages/codemods/nuxt/4/shallow-data-reactivity/__testfixtures__/fixture1.input.ts
packages/codemods/nuxt/4/shallow-data-reactivity/__testfixtures__/fixture1.output.ts
packages/codemods/nuxt/4/shallow-data-reactivity/package.json
packages/codemods/nuxt/4/shallow-data-reactivity/src/index.ts
packages/codemods/nuxt/4/shallow-data-reactivity/tsconfig.json
packages/codemods/nuxt/4/shallow-data-reactivity/vitest.config.ts
pnpm-lock.yaml

This PR adds a codemod for Nuxt 4 Shallow Data Reactivity as requested in #692.

[codemod request] Nuxt 4: add nuxt/4/shallow-data-reactivity

---

packages/codemods/react/19/replace-reactdom-render/.codemodrc.json
packages/codemods/react/19/replace-reactdom-render/README.md
packages/codemods/react/19/replace-reactdom-render/__testfixtures__/hydrate.input.js
packages/codemods/react/19/replace-reactdom-render/__testfixtures__/hydrate.output.js
packages/codemods/react/19/replace-reactdom-render/__testfixtures__/import.input.js
packages/codemods/react/19/replace-reactdom-render/__testfixtures__/import.output.js
packages/codemods/react/19/replace-reactdom-render/src/index.ts
packages/codemods/react/19/replace-reactdom-render/test/test.ts
packages/codemods/vue/3/render-function-api/.codemodrc.json
packages/codemods/vue/3/render-function-api/src/index.ts

[Registry]: react/19/replace-reactdom-render support `hydrate` method

---

packages/codemods/react/19/migration-recipe/.codemodrc.json
packages/codemods/react/prop-types-typescript/.codemodrc.json

[Registry] react/19/migration-recipe add deps, react/prop-types-typescript change include pattern

---

apps/frontend/app/(website)/studio/main/modGPT/useAiService/useModGpt/useModGptSubmit.ts

console log removal

---

packages/codemods/react/19/remove-memoization/.codemodrc.json
packages/codemods/react/19/remove-memoization/README.md

Adds a safety warning for React 19 `remove-memoization` codemod.

[codemods] React 19: Add remove-memoization safety note

---

apps/frontend/app/(website)/studio/main/modGPT/useAiService/codemodAI/useCodemodAI.tsx
apps/frontend/app/(website)/studio/main/modGPT/useAiService/useAiService.ts

[studio] fix generate codemod button behaviour

---

apps/frontend/app/(website)/studio/main/modGPT/config.ts

studio - ws path update

---

apps/frontend/app/(website)/studio/main/modGPT/useAiService/codemodAI/useCodemodAI.tsx

ws auth disabled

---

packages/utilities/package.json

trigger redeployment

---

apps/frontend/components/templates/Registry/helpers.ts
packages/codemods/msw/2/upgrade-recipe/.codemodrc.json

[Regiatry] Fix framework label

---

apps/frontend/app/(website)/studio/main/modGPT/useAiService/codemodAI/useCodemodAI.tsx

revert token

---

apps/frontend/app/(website)/studio/main/modGPT/config.ts
apps/frontend/app/(website)/studio/main/modGPT/useAiService/codemodAI/useCodemodAI.tsx

studio - socket-io remove

---

apps/frontend/app/(website)/studio/main/modGPT/useAiService/codemodAI/useCodemodAI.tsx
apps/frontend/app/(website)/studio/main/modGPT/useAiService/useAiService.ts

set token on iterative codemod build

---

apps/frontend/app/(website)/studio/main/modGPT/config.ts
apps/modgpt/package.json
apps/modgpt/src/dev-utils/consts.ts

modgpt llmEngines updated

---

apps/backend/src/schemata/schema.ts
apps/frontend/app/(website)/studio/main/modGPT/config.ts

BE: new engines added

---

apps/modgpt/src/init.ts
apps/modgpt/src/routes/index.ts
apps/modgpt/src/routes/sendChat.ts
apps/modgpt/src/schemata/env.ts
apps/modgpt/ui/index.html
apps/modgpt/ui/script.js

Remove unneeded imports, fix ui port

[modgpt] import and port fix

---

apps/vsce/src/codemods/types.ts
apps/vsce/src/components/engineService.ts
apps/vsce/src/extension.ts
apps/vsce/src/selectors/selectCodemodTree.ts
apps/vsce/webview/src/codemodList/CodemodArguments/FormField/index.tsx
apps/vsce/webview/src/codemodList/CodemodArguments/index.tsx
apps/vsce/webview/src/codemodList/CodemodArguments/styles.module.css
apps/vsce/webview/src/codemodList/CodemodNodeRenderer/Codemod.tsx
apps/vsce/webview/src/customTreeView.tsx

[vsce] support enum arg type

---

apps/docs/codemod-registry/publishing-codemods.mdx

Minor adjustments to codemod package readme reference.

[docs] remove description heading from readme reference

---

apps/docs/codemod-registry/publishing-codemods.mdx

Adds pros of adding applicability criteria field to published codemod.

[docs] add pros of adding applicability criteria field

---

apps/frontend/app/(website)/studio/page.tsx

always use white theme when in studio

use light theme in studio

---

apps/frontend/styles/globals.css

style fix - \<code\> element before/after style fix

studio code interpolation style fix

---

apps/vsce/src/components/engineService.ts
apps/vsce/src/components/messageBus.ts
apps/vsce/src/components/webview/MainProvider.ts
apps/vsce/src/extension.ts

- [vsce] "Codemod didn't do anything" message should not appear if there are changes
- [vsce] Refactor outdated logic and trim it down (CLI  runner now only supports 2 kinds: "finish" / "progress"; not any more kinds like "rewrite", "create", "move", etc types)

[vsce] 2 tickets: CDMD-3497, CDMD-3493

---

apps/docs/codemod-registry/publishing-codemods.mdx

Explaining daisy chaining codemods.

[docs] add explanation for daisy chaining codemods

---

packages/codemods/react/19/replace-act-import/.codemodrc.json
packages/codemods/react/19/replace-act-import/__testfixtures__/fixture4.output.js
packages/codemods/react/19/replace-act-import/src/index.ts
packages/codemods/react/19/replace-act-import/test/test.ts

- add isDirty flag to fix formatting of files that were not transformed

[registry] react/19/act add isDirty flag

---

packages/codemods/next/13/replace-use-search-params/README.md

Fixes any invalid readme content found.

[registry] audit readme content

---

apps/cli/package.json
apps/cli/src/buildOptions.ts

dont show git check opt-out option to the user

---

packages/workflow/examples/codemod@2.0.ts
packages/workflow/examples/git-example.ts
packages/workflow/package.json
packages/workflow/src/ai/ai.ts
packages/workflow/src/astGrep/astGrep.ts
packages/workflow/src/astGrep/map.ts
packages/workflow/src/astGrep/replace.ts
packages/workflow/src/codemod.ts
packages/workflow/src/contexts.ts
packages/workflow/src/engineHelpers.ts
packages/workflow/src/exec.ts
packages/workflow/src/git.ts
packages/workflow/src/jsFiles.ts
pnpm-lock.yaml

Initial PR for codemod2.0

---

apps/cli/package.json
packages/workflow/package.json
packages/workflow/src/ai/ai.ts

Update package versions and api key argument

---

apps/cli/package.json
packages/workflow/package.json
packages/workflow/src/ai/ai.ts

switch back to gpt4

---

packages/codemods/devcycle/launchdarkly-to-devcycle/tsconfig.json
packages/codemods/devcycle/replace-feature-flag/tsconfig.json
packages/codemods/netlify/replace-feature-flag/tsconfig.json
packages/codemods/nuxt/4/shallow-data-reactivity/tsconfig.json
packages/codemods/openFeature/replace-feature-flags/tsconfig.json
packages/codemods/react/19/replace-act-import/tsconfig.json
packages/codemods/react/19/replace-reactdom-render/.codemodrc.json
packages/codemods/react/19/replace-reactdom-render/src/index.ts
packages/codemods/react/19/replace-reactdom-render/tsconfig.json
packages/codemods/react/19/replace-string-ref/tsconfig.json
packages/codemods/react/19/replace-use-form-state/tsconfig.json
packages/codemods/statsig/replace-gate/tsconfig.json
packages/codemods/vue/3/render-function-api/tsconfig.json
packages/utilities/src/package-boilerplate.ts

- update tsconfigs for codemods
- update the codemod init boilerplate
- fix reactdom-render codemod

fix [Registry]: fix reactdom-render codemod

---

apps/frontend/app/(website)/registry/[codemod]/page.tsx
apps/frontend/data/codemod/loaders.ts

cache fix attempt1

---

apps/frontend/app/(website)/registry/[codemod]/page.tsx

restore revalidation timouut

---

apps/cli/src/analytics/telemetry.ts
apps/cli/src/commands/publish.ts
apps/cli/src/executeMainThread.ts

- add codemod publish even tracking

feat [CLI]: track publish event

---

packages/codemods/netlify/add-zod-validation/.codemodrc.json
packages/codemods/netlify/add-zod-validation/.gitignore
packages/codemods/netlify/add-zod-validation/LICENSE
packages/codemods/netlify/add-zod-validation/README.md
packages/codemods/netlify/add-zod-validation/__testfixtures__/fixture1.input.ts
packages/codemods/netlify/add-zod-validation/__testfixtures__/fixture1.output.ts
packages/codemods/netlify/add-zod-validation/__testfixtures__/fixture2.input.ts
packages/codemods/netlify/add-zod-validation/__testfixtures__/fixture2.output.ts
packages/codemods/netlify/add-zod-validation/__testfixtures__/fixture3.input.ts
packages/codemods/netlify/add-zod-validation/__testfixtures__/fixture3.output.ts
packages/codemods/netlify/add-zod-validation/package.json
packages/codemods/netlify/add-zod-validation/src/index.ts
packages/codemods/netlify/add-zod-validation/tsconfig.json
packages/codemods/netlify/add-zod-validation/vitest.config.ts
pnpm-lock.yaml

Add zod validation codemod

---

apps/frontend/app/(website)/registry/[codemod]/page.tsx
apps/frontend/components/templates/CodemodPage/parts/Code.tsx
apps/frontend/data/codemod/loaders.ts

fix horyzontal overflow, add types for fetchWithTimeout

---

apps/docs/deploying-codemods/cli.mdx

- improve include/exclude options wording
- add unpublishing guide
- clean up commands wording

[docs] update cli docs

---

apps/docs/building-codemods/getting-started.mdx
apps/docs/codemod-registry/introduction.mdx
apps/docs/codemod-registry/publishing-codemods.mdx
apps/docs/deploying-codemods/cli.mdx
apps/docs/deploying-codemods/introduction.mdx
apps/docs/deploying-codemods/vsce.mdx

[docs] adjust naming

---

apps/frontend/app/(website)/studio/features/FirstLoginExperience/FirstLoginExperience.tsx

check if signin exists

---

apps/backend/package.json
apps/backend/src/publishHandler.test.ts
apps/backend/src/publishHandler.ts
apps/backend/src/unpublishHandler.ts

- allow unpublishing anything for verified users 
- disallow publishing under the same name if it was taken

[Backend] fix: publishing rules (CDMD-3527, CDMD-3582)

---

apps/cli/src/commands/init.ts
apps/cli/src/commands/publish.ts

- ask for readme adjustments before publishing if its a single file codemod
- print a warning if its a bundle and readme was not found
- skip upload altogether if user chooses to force

[CLI] feat: readme branching during publish (CDMD-3438)

---

apps/backend/package.json
apps/backend/src/cron.ts
apps/backend/src/services/PostHogService.ts

[Backend]: fix: posthog cronjob trycatch

---

apps/docs/deploying-codemods/cli.mdx

Adds `codemod publish` `--source` option.

[docs] add codemod publish source option

---

apps/cli/package.json
apps/cli/src/commands/build.ts
apps/cli/src/commands/feedback.ts
apps/cli/src/commands/learn.ts
apps/cli/src/commands/list.ts
apps/cli/src/commands/login.ts
apps/cli/src/commands/logout.ts
apps/cli/src/commands/publish.ts
apps/cli/src/commands/run.ts
apps/cli/src/commands/unpublish.ts
apps/cli/src/commands/whoami.ts
apps/cli/src/executeMainThread.ts

[CLI] feat: add feedback command, conform function arguments passing

---

apps/frontend/middleware.ts

Fix middleware

---

packages/runner/src/fileCommands.ts
packages/runner/src/index.ts
packages/utilities/package.json
packages/utilities/src/functions/formatting.ts
packages/utilities/src/index.ts
packages/workflow/package.json
packages/workflow/src/ai/ai.ts
packages/workflow/src/astGrep/astGrep.ts
packages/workflow/src/engineHelpers.ts
packages/workflow/src/git/clone.ts
pnpm-lock.yaml

Added formatting to workflow engine

---

apps/frontend/styles/globals.css

[frontend] sign-up text is not visible in clerk auth component - cdmd-3612

---

apps/frontend/middleware.ts

[Registry-www] temporarily allow unsafe-inline

---

apps/frontend/middleware.ts

[Registry-www] fix middleware 2

---

apps/frontend/middleware.ts

[Registry-www] Fix middleware

---

apps/frontend/middleware.ts

[Registry-www]: fix sanity live editing CSP

---

apps/backend/package.json
apps/backend/src/publishHandler.ts
apps/backend/src/revalidate.ts
apps/backend/src/unpublishHandler.ts
apps/frontend/app/(website)/registry/[codemod]/page.tsx
apps/frontend/data/sanity/loadQuery.ts

fix revalidation

---

packages/runner/package.json
packages/runner/src/schemata/codemodSettingsSchema.ts

- fixes the issue where cli throws `Codemod to run was not specified!` when you pass only `--source`  flag

[CLI] fix run sourced

---

apps/docs/codemod-registry/introduction.mdx

[docs] fix: remove leftover overview link

---

apps/docs/platform/run.mdx

Updated run section based on feedback.

[docs] update run section

---

apps/docs/deploying-codemods/cli.mdx

Fixes `codemod feedback` command in Codemod CLI doc.

[docs] fix codemod feedback command

---

apps/cli/package.json
packages/runner/src/runWorkflowCodemod.ts
packages/utilities/src/package-boilerplate.ts
packages/workflow/package.json
packages/workflow/src/fs.ts
packages/workflow/tsconfig.json
pnpm-lock.yaml

fixed workflow dependencies

---

apps/frontend/app/(website)/studio/features/modGPT/utils.ts

Button name changed to "Autogenerate with AI"

[studio] button name change

---

apps/frontend/app/(website)/studio/src/store/zustand/CFS/index.ts
apps/shared/consts.ts

[studio] gpt-4o as default engine

---

.github/ISSUE_TEMPLATE/request-codemod.md

Update request-codemod template

---

apps/backend/src/server.ts
apps/task-manager/package.json
apps/task-manager/src/worker.ts
packages/utilities/src/schemata/codemodRunSchema.ts
pnpm-lock.yaml

[Backend]: GH Run removed name 

---

packages/codemods/axios/fetch/.codemodrc.json
packages/codemods/axios/fetch/.gitignore
packages/codemods/axios/fetch/LICENSE
packages/codemods/axios/fetch/README.md
packages/codemods/axios/fetch/__testfixtures__/fixture1.input.ts
packages/codemods/axios/fetch/__testfixtures__/fixture1.output.ts
packages/codemods/axios/fetch/__testfixtures__/fixture2.input.ts
packages/codemods/axios/fetch/__testfixtures__/fixture2.output.ts
packages/codemods/axios/fetch/package.json
packages/codemods/axios/fetch/src/index.ts
packages/codemods/axios/fetch/tsconfig.json
pnpm-lock.yaml

axios to fetch codemod

---

apps/cli/src/commands/init.ts
apps/cli/src/downloadCodemod.ts
pnpm-lock.yaml

[CLI] fix: messaging for git url (CDMD-3664)

---

.github/ISSUE_TEMPLATE/report-faulty-codemod.md

Update report-faulty-codemod template

---

.github/workflows/auth-backend-ci-cd.yml

[Backend]: workflow fix

---

apps/auth-service/Dockerfile
apps/auth-service/esbuild.config.js
apps/backend/Dockerfile
apps/backend/esbuild.config.js

[backend]: fix dockerfiles

---

apps/backend/Dockerfile

[backend] fix dockerfiles

---

apps/backend/Dockerfile
apps/backend/esbuild.config.js

[backend]fix dockerfile

---

apps/auth-service/Dockerfile
apps/auth-service/esbuild.config.js

[backend]: fix auth dockerfile

---

apps/modgpt/package.json
apps/modgpt/src/init.ts
apps/modgpt/src/plugins/authPlugin.ts
apps/modgpt/src/routes/sendChat.ts
apps/modgpt/src/schemata/env.ts
pnpm-lock.yaml

[Backend]: modGPT use auth service

---

apps/auth-service/Dockerfile
apps/auth-service/package.json
apps/backend/Dockerfile
apps/backend/package.json

[Backend]: fixed migrations

---

apps/auth-service/Dockerfile
apps/auth-service/package.json
apps/backend/Dockerfile
apps/backend/package.json

[backend]fixed migrations

---

apps/modgpt/package.json
apps/modgpt/src/routes/sendChat.ts

[backend]: fixed auth

---

apps/modgpt/package.json
apps/modgpt/src/plugins/authPlugin.ts

[backend]: debug

---

packages/codemods/react/19/replace-react-test-renderer-import/.codemodrc.json
packages/codemods/react/19/replace-react-test-renderer-import/LICENSE
packages/codemods/react/19/replace-react-test-renderer-import/README.md
packages/codemods/react/19/replace-react-test-renderer-import/__testfixtures__/import-cjs.input.ts
packages/codemods/react/19/replace-react-test-renderer-import/__testfixtures__/import-cjs.output.ts
packages/codemods/react/19/replace-react-test-renderer-import/__testfixtures__/import-esm.input.ts
packages/codemods/react/19/replace-react-test-renderer-import/__testfixtures__/import-esm.output.ts
packages/codemods/react/19/replace-react-test-renderer-import/__testfixtures__/no-import.input.ts
packages/codemods/react/19/replace-react-test-renderer-import/package-lock.json
packages/codemods/react/19/replace-react-test-renderer-import/package.json
packages/codemods/react/19/replace-react-test-renderer-import/src/index.ts
packages/codemods/react/19/replace-react-test-renderer-import/test/test.ts
packages/codemods/react/19/replace-react-test-renderer-import/tsconfig.json
packages/codemods/react/19/replace-react-test-renderer-import/vitest.config.ts
pnpm-lock.yaml

add replace-react-test-renderer-import

---

.github/ISSUE_TEMPLATE/studio-bug

Adds a template for Codemod Studio issues.

Create Codemod Studio Issue template

---

apps/frontend/app/(website)/studio/features/FirstLoginExperience/FirstLoginExperience.tsx
apps/frontend/app/(website)/studio/main/Header/TopBar.tsx
apps/frontend/app/(website)/studio/src/components/button/IconButton.tsx

[studio] buttons to header added

---

apps/cli/package.json

bump cli version

---

apps/frontend/app/(website)/studio/src/index.css
apps/frontend/app/(website)/studio/src/studio.css

highlight colors in diff fix

---

packages/codemods/nuxt/4/default-data-error-value/.codemodrc.json
packages/codemods/nuxt/4/default-data-error-value/.gitignore
packages/codemods/nuxt/4/default-data-error-value/LICENSE
packages/codemods/nuxt/4/default-data-error-value/README.md
packages/codemods/nuxt/4/default-data-error-value/__testfixtures__/fixture1.input.ts
packages/codemods/nuxt/4/default-data-error-value/__testfixtures__/fixture1.output.ts
packages/codemods/nuxt/4/default-data-error-value/package.json
packages/codemods/nuxt/4/default-data-error-value/src/index.ts
packages/codemods/nuxt/4/default-data-error-value/tsconfig.json
packages/codemods/nuxt/4/default-data-error-value/vitest.config.ts

- the codemod updates the default value of data and error to undefined
- https://go.codemod.com/MBUBBKj
https://www.loom.com/share/ab25a5b86fcb4a5fbd2e844ab526ce6b
-   **What is the current behavior?** (You can …

feat: add codemod for default value updates

---

apps/run-service/Dockerfile
apps/run-service/package.json

[backend]: run service fix

---

.github/workflows/test.yml
packages/codemods/react/19/remove-forward-ref/src/index.ts
packages/codemods/react/19/replace-create-factory/.codemodrc.json
packages/codemods/react/19/replace-create-factory/.gitignore
packages/codemods/react/19/replace-create-factory/LICENSE
packages/codemods/react/19/replace-create-factory/README.md
packages/codemods/react/19/replace-create-factory/__testfixtures__/identifier.input.ts
packages/codemods/react/19/replace-create-factory/__testfixtures__/identifier.output.ts
packages/codemods/react/19/replace-create-factory/__testfixtures__/string-tag-name.input.ts
packages/codemods/react/19/replace-create-factory/__testfixtures__/string-tag-name.output.ts
packages/codemods/react/19/replace-create-factory/package.json
packages/codemods/react/19/replace-create-factory/src/analyze.ts
packages/codemods/react/19/replace-create-factory/src/index.ts
packages/codemods/react/19/replace-create-factory/test/test.ts
packages/codemods/react/19/replace-create-factory/tsconfig.json
packages/codemods/react/19/replace-create-factory/vitest.config.ts
packages/jscodeshift-utils/README.md
packages/jscodeshift-utils/__testfixtures__/import-add-1.input.ts
packages/jscodeshift-utils/__testfixtures__/import-add-1.output.ts
packages/jscodeshift-utils/package.json
packages/jscodeshift-utils/src/callExpression.ts
packages/jscodeshift-utils/src/import.ts
packages/jscodeshift-utils/src/index.ts
packages/jscodeshift-utils/test/test.ts
packages/jscodeshift-utils/tsconfig.json
pnpm-lock.yaml

[codemods] add react/19/replace-create-factory codemod, add jscodeshift utils package

---

apps/cli/package.json
apps/cli/src/buildOptions.ts
apps/cli/src/commands/run.ts
apps/docs/deploying-codemods/cli.mdx
packages/printer/src/utils.ts
pnpm-lock.yaml

[CLI] feat: print config or manual of the codemod (CDMD-3584)

---

apps/frontend/app/(website)/studio/features/modGPT/ChatWindow/ModelSelector.tsx
apps/frontend/app/(website)/studio/features/modGPT/PromptPanel/PromptPanel.tsx
apps/frontend/app/(website)/studio/features/modGPT/config.ts
apps/frontend/app/(website)/studio/features/modGPT/useAiService/codemodAI/useCodemodAI.tsx
apps/frontend/app/(website)/studio/features/modGPT/useAiService/useModGpt/useModGpt.ts
apps/frontend/app/(website)/studio/features/modGPT/utils.ts
apps/frontend/app/(website)/studio/src/store/zustand/CFS/index.ts

Codemod AI generation published to main

remove references to shouldUseCodemodAI

---

apps/frontend/app/(website)/studio/main/Header/TopBar.tsx

redirect from studio is broken for signing out

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/test.yml
apps/auth-service/package.json
apps/auth-service/src/server.ts
apps/backend/package.json
apps/backend/src/cron.ts
apps/backend/src/schemata/env.ts
pnpm-lock.yaml

- created basic cronjob to notify about system health

[Backend]: health-check alert cronjob.

---

apps/frontend/app/(website)/studio/features/GHRun/hooks/useCodemodExecution.ts

trigger deployment

---

apps/frontend/middleware.ts

fix redirects

---

apps/frontend/app/(website)/studio/features/modGPT/useAiService/codemodAI/useCodemodAI.tsx

socket removal

---

apps/frontend/components/templates/CodemodPage/CodemodPageUI.tsx
apps/frontend/components/templates/Registry/RegistryCard.tsx

made for removed and tags unique by name

---

apps/frontend/components/TokenBuilder.tsx

[Frontend] feat: show login notice for user (CDMD-3557)

---

apps/cli/package.json
apps/cli/src/commands/feedback.ts
apps/cli/src/commands/learn.ts
apps/cli/src/commands/login.ts
apps/cli/src/utils.ts
pnpm-lock.yaml

[CLI] fix: use open library for opening URLs in CLI

---

.github/ISSUE_TEMPLATE/report-faulty-codemod.md

changing the title and description of the issue.

Update report-faulty-codemod.md title and description

---

apps/frontend/app/(website)/studio/src/store/getInitialState.ts

This PR swaps the default example in Codemod Studio for a more interesting one.

Change the default sample for jscodeshift

---

.github/ISSUE_TEMPLATE/studio-bug.md

Update studio-bug.md title and description

Update studio-bug.md title and description

---

.github/ISSUE_TEMPLATE/request-codemod.md

nits - Update request-codemod.md title and description

Update request-codemod.md title and description

---

apps/frontend/app/(website)/studio/main/Header/TopBar.tsx

update community link to studio/chore/community-link-update

[studio] community link update

---

apps/cli/package.json
packages/codemods/pnpm/catalog/.codemodrc.json
packages/codemods/pnpm/catalog/README.md
packages/codemods/pnpm/catalog/package.json
packages/codemods/pnpm/catalog/src/index.ts
packages/codemods/pnpm/catalog/vitest.config.ts
packages/runner/src/runCodemod.ts
packages/runner/src/runWorkflowCodemod.ts
packages/workflow/build.js
packages/workflow/package.json
packages/workflow/src/contexts/FileContext.ts
packages/workflow/src/json/update.ts
packages/workflow/src/yaml/update.ts
pnpm-lock.yaml

preserve json files formatting, update pnpm catalog logic

---

packages/codemods/react-native/74/migrate-to-fire-interval-seconds/.codemodrc.json
packages/codemods/react-native/74/migrate-to-fire-interval-seconds/README.md
packages/codemods/react-native/74/remove-alert-action/.codemodrc.json
packages/codemods/react-native/74/remove-alert-action/README.md
packages/codemods/react-native/74/remove-event-listener-callback/.codemodrc.json
packages/codemods/react-native/74/remove-event-listener-callback/README.md

Update react-native codemods README

---

apps/frontend/app/(website)/studio/features/FirstLoginExperience/config.tsx

[studio] simplify onboarding

---

packages/codemods/typescript/use-template-literals/.codemodrc.json

[codemod] use-ts-literals update codemodrc

---

packages/codemods/msw/2/response-usages/__testfixtures__/fixture1.input.ts
packages/codemods/msw/2/response-usages/__testfixtures__/fixture1.output.ts
packages/codemods/msw/2/response-usages/__testfixtures__/fixture2.input.ts
packages/codemods/msw/2/response-usages/__testfixtures__/fixture2.output.ts
packages/codemods/msw/2/response-usages/__testfixtures__/fixture3.input.ts
packages/codemods/msw/2/response-usages/__testfixtures__/fixture3.output.ts
packages/codemods/msw/2/response-usages/package.json
packages/codemods/msw/2/response-usages/src/index.ts
packages/codemods/msw/2/response-usages/test/test.ts

Addresses issues described in #916 & #917

[Codemods] fix: msw response-usages codemod FNs/FPs (CDMD-3689)

---

apps/backend/src/publishHandler.test.ts
apps/backend/src/publishHandler.ts
apps/backend/src/schemata/env.ts
apps/cli/src/commands/build.ts
apps/cli/src/commands/init.ts
apps/cli/src/commands/publish.ts
packages/utilities/src/package-boilerplate.ts
packages/utilities/src/schemata/codemodConfigSchema.ts
pnpm-lock.yaml
vitest.config.ts

- ask about tags and git url during publish
- fix validation issues

[CLI] fix: validate git url, add question for tags (CDMD-3556)

---

apps/cli/package.json
apps/cli/src/executeMainThread.ts

[Telemetry] fix: fix telemetry logging

---

apps/cli/package.json

[CLI] fix: fix version

---

apps/frontend/app/(website)/studio/src/store/getInitialState.ts
apps/frontend/app/(website)/studio/src/store/utils/getSnippetInitialState.ts

bring back the correct snippets

snippets udpate

---

apps/frontend/app/(website)/studio/features/modGPT/prompts.ts

In this PR I updated ModGPT's prompt to become similar to Codemod AI's initial prompt.

[studio] align ModGPT prompt with Codemod AI initial prompt

---

.github/workflows/build.yml
pnpm-lock.yaml

[workflow] fix: removed doubled variable

---

packages/codemods/react/19/replace-use-form-state/.codemodrc.json

Fixed issue with react 19 use-form-state

---

apps/frontend/app/(website)/studio/main/PageBottomPane/TestTabsComponent.tsx
apps/frontend/app/(website)/studio/src/store/snippets.ts
apps/frontend/styles/globals.css

Added horizontal scrolling when tests cases are longer than a viewport

[studio] feature: max test cases and overflow

---

apps/frontend/app/(website)/studio/features/FirstLoginExperience/config.tsx
apps/frontend/app/(website)/studio/src/store/initialState.ts

This PR updates the default codemod and the tour to align with the latest button and tab names.

[studio] fix: update helper texts

---

apps/cli/src/commands/run.ts

after codemod run, show more concise messaging for logs and feedback.

chore(cli): more concise messaging after codemod run

---

apps/cli/package.json
packages/runner/src/runCodemod.ts

fix(cli): fix patterns builder for win

---

apps/frontend/app/(website)/studio/src/hooks/useCodeDiff.ts
apps/frontend/app/(website)/studio/src/store/mod.ts

[studio] feat: prettify actual output

---

apps/frontend/styles/globals.css

[studio] fix: css typo fixed

---

apps/backend/Dockerfile
apps/backend/package.json

feat(backend): fix and update Dockerfile

---

apps/frontend/app/(website)/studio/main/ASTViewer/AboristViewer.tsx
apps/frontend/app/(website)/studio/main/ASTViewer/useScrollNodeIntoView.ts

- removed console log
- fix the id issue

[studio] fix: ast id improvement

---

apps/backend/Dockerfile
apps/backend/package.json

feat(backend): updated Dockerfile

---

apps/backend/package.json
apps/backend/src/cron.ts

feat(backend): fixed health-check cron time

---

apps/frontend/app/(website)/studio/src/store/mod.ts

fix(studio): remove formatting when changing in studio

---

packages/codemods/nuxt/4/migration-recipe/.codemodrc.json
packages/codemods/nuxt/4/migration-recipe/README.md

docs(codemod-nuxt-4): fixed list of codemods

---

apps/cli/package.json
packages/workflow/package.json
packages/workflow/src/contexts/FileContext.ts
packages/workflow/src/jsFiles.ts

There is an issue when there are multiple replacements, this fixes an issue.

fix(workflow engine): fix incorrect replacement ranges

---

apps/cli/package.json
apps/cli/src/buildOptions.ts
apps/docs/deploying-codemods/cli.mdx
packages/runner/src/schemata/flowSettingsSchema.ts
packages/workflow/package.json
packages/workflow/src/contexts/FileContext.ts
packages/workflow/src/json/update.ts
packages/workflow/src/yaml/update.ts

feat(cli): disable formatting with prettier by default for cli

---

pull_request_template.md

doc: Update pull_request_template

---

apps/frontend/app/(website)/studio/main/ASTViewer/useSelectFirstTreeNodeForSnippet.ts
apps/frontend/app/(website)/studio/main/Codemod.tsx
apps/frontend/app/(website)/studio/src/hooks/useCodeDiff.ts
apps/frontend/app/(website)/studio/src/schemata/stateSchemata.ts
apps/frontend/app/(website)/studio/src/store/snippets.ts

Fixed the logic behind initial state inilatization

fix(studio): initial state fixed

---

apps/frontend/app/(website)/studio/main/PageBottomPane/Components/Snippets/CodeSnippets.tsx
apps/frontend/app/(website)/studio/src/components/Snippet/MonacoDiffEditor.tsx
apps/frontend/app/(website)/studio/src/components/Snippet/SnippetUI.tsx
apps/frontend/app/(website)/studio/src/components/Snippet/consts.ts
apps/frontend/app/(website)/studio/src/hooks/useCodeDiff.ts
apps/frontend/app/(website)/studio/src/studio.css
apps/frontend/styles/globals.css

fix(studio): editors overlays fix

---

apps/cli/src/buildCodemodOptions.ts
apps/cli/src/codemodConfig.ts
apps/cli/src/commands/build.ts
apps/cli/src/commands/run.ts
apps/cli/src/downloadCodemod.ts

Adds a reusable function to read and parse the codemodrc file.
- **What kind of change does this PR introduce?**
Refactor
- **What is the current behavior?**
---
No behavior changes
- **Does this PR introduce a breaking change?**
no

refactor(CLI): Reusable function for reading and parsing codemodrc

---

apps/frontend/app/(website)/studio/features/modGPT/PromptPanel/PromptPanel.tsx
apps/frontend/app/(website)/studio/features/modGPT/PromptPanel/index.ts
apps/frontend/app/(website)/studio/features/modGPT/utils.ts
apps/frontend/app/(website)/studio/src/hooks/useCodeDiff.ts

feat(studio): remove legacy ai button

---

apps/cli/src/main.ts
pnpm-lock.yaml

Fix the issue where telemetry flush is not called for some commands.

fix(cli): fix telemetry dispose

---

apps/cli/package.json
apps/cli/src/commands/init.ts
apps/cli/src/commands/learn.ts
apps/cli/src/commands/run.ts
apps/cli/src/fetch-codemod.ts
packages/database/tsconfig.json
packages/runner/src/source-code.ts
packages/utilities/src/functions/validation.ts
packages/utilities/src/package-boilerplate.ts
packages/utilities/src/schemata/codemod-config.ts
packages/utilities/src/schemata/codemod.ts

- fix standalone runs
- init engine questions now depend on file extension
- allow running recipe from codemodrc directly
- improve posthog logs
- attempt to fix building error

fix(cli): standalone runs related improvements

---

apps/cli/build.js
apps/cli/package.json
apps/cli/src/credentials-storage.ts
packages/runner/package.json
pnpm-lock.yaml

- replace keytar with keyring-rs
- add underscore package to prevent potential build error in runner (vue-sfc)

fix(cli): replace keytar with keyring-rs

---

apps/frontend/app/(website)/studio/features/codemod-apply/useCodemodOutputUpdate.ts
apps/frontend/app/(website)/studio/features/codemod-apply/useWebWorker.ts
apps/frontend/app/(website)/studio/main/Log/Table.tsx
apps/frontend/app/(website)/studio/main/Log/TableBlock.tsx
apps/frontend/app/(website)/studio/main/Log/utils.ts
apps/frontend/app/(website)/studio/src/store/log.ts

Tidy up debugger, spliced events to categories, fix issues with console.logs in codemod code

feat(studio): debugger improvements

---

apps/cli/src/commands/init.ts
apps/cli/src/commands/publish.ts
apps/cli/src/credentials-storage.ts
apps/cli/src/fetch-codemod.ts
apps/cli/src/main.ts
apps/cli/src/utils.ts
pnpm-lock.yaml

- fixes naming in function variables
- target path now works and is being created if it does not exist
- adds npm installation progress
- removes existsSync in favor of access

fix(cli): init command target and installation progress

---

apps/cli/src/credentials-storage.ts
apps/cli/src/fetch-codemod.ts
packages/runner/src/source-code.ts

dependencies are taken into account now for standalone codemods

fix(cli): bundle standalone codemods before running

---

apps/frontend/app/(website)/studio/features/modGPT/ChatWindow/ChatMessage/CodeBlock.tsx

feat(studio): copy button title added

---

apps/cli/package.json
packages/codemods/sql/add-index-before-select/.codemodrc.json
packages/codemods/sql/add-index-before-select/.gitignore
packages/codemods/sql/add-index-before-select/LICENSE
packages/codemods/sql/add-index-before-select/README.md
packages/codemods/sql/add-index-before-select/__testfixtures__/fixture1.input.sql
packages/codemods/sql/add-index-before-select/__testfixtures__/fixture1.output.sql
packages/codemods/sql/add-index-before-select/package.json
packages/codemods/sql/add-index-before-select/src/index.ts
packages/codemods/sql/add-index-before-select/tsconfig.json
packages/workflow/package.json
packages/workflow/src/astGrep/astGrep.ts
packages/workflow/src/index.ts
pnpm-lock.yaml
pnpm-workspace.yaml

Updated ast-grep to latest version with SQL support
Added sample codemod for adding SQL index

feat(codemods): added sample codemod for adding index based on select query for sql files

---

apps/frontend/app/(website)/studio/main/PaneLayout/LoginWarningModal.tsx

fix(studio): codemod learn modal style fixes

---

apps/cli/Dockerfile
apps/cli/build.js
apps/cli/package.json
apps/cli/src/credentials-storage.ts
pnpm-lock.yaml

- bring back keytar library and use dynamic import to handle initialization error, tested in docker image with different linux distributions
- update dockerfile

fix(cli): libsecret missing handling (CDMD-3823)

---

apps/frontend/app/(website)/studio/features/ThemeSwitcher/StudioThemeSwitcher.tsx
apps/frontend/app/(website)/studio/features/ThemeSwitcher/addCSS.ts
apps/frontend/app/(website)/studio/features/ThemeSwitcher/index.ts
apps/frontend/app/(website)/studio/features/ThemeSwitcher/setMode.ts
apps/frontend/app/(website)/studio/main/Header/TopBar.tsx
apps/frontend/components/global/Footer/ThemeSwitcher.tsx
apps/frontend/components/global/Footer/index.tsx

feat(studio): dark mode

---

apps/docs/guides/engines/workflow-engine/api-reference.mdx

add more details for executing cli commands.
tested only manually on github markdown. not mintlify.

docs(workflow-engine): add more details for executing cli commands.

---

apps/frontend/app/(website)/studio/features/ThemeSwitcher/StudioThemeSwitcher.tsx
apps/frontend/app/(website)/studio/features/ThemeSwitcher/setMode.ts

Fixed the initial behavior of theme

fix(studio): theme fix

---

packages/workflow/src/contexts.ts

Create git context when it is used outside clone

fix(workflow-engine): return git context outside clone

---

apps/frontend/app/(website)/studio/features/modGPT/Chat.tsx
apps/frontend/app/(website)/studio/features/modGPT/PromptPanel/GenerateTestCasesButton.tsx
apps/frontend/app/(website)/studio/features/modGPT/PromptPanel/PromptPanel.tsx
apps/frontend/app/(website)/studio/features/modGPT/PromptPanel/WebSocketButton.tsx
apps/frontend/app/(website)/studio/features/modGPT/prompts.ts
apps/frontend/app/(website)/studio/features/modGPT/useAiService/codemodAI/useCodemodAI.tsx
apps/frontend/app/(website)/studio/features/modGPT/useAiService/useAiService.ts
apps/frontend/app/(website)/studio/main/5PaneSetup.tsx
apps/frontend/app/(website)/studio/main/PageBottomPane/TestTabsComponent.tsx
apps/frontend/app/(website)/studio/main/PaneLayout/AssistantTabs.tsx
apps/frontend/app/(website)/studio/main/PaneLayout/tabsData.tsx
apps/frontend/app/(website)/studio/src/store/mod.ts
apps/frontend/app/(website)/studio/src/store/snippets.ts

feat(studio): autogenerated test cases

---

apps/backend/Dockerfile
apps/backend/package.json

chore(backend): added migration script to the backend Dockerfile and removed prisma.schema path

---

apps/auth-service/package.json
apps/auth-service/src/server.ts
apps/backend/package.json
apps/backend/src/server.ts
apps/modgpt/package.json
apps/modgpt/src/dev-utils/cors.ts
apps/run-service/package.json
apps/run-service/src/server.ts

- added staging CORS policy
- bumped versions

chore(backend, auth, modgpt, run): added staging CORS policy

---

.github/workflows/auth-backend-ci-cd-staging.yml

- added staging CI/CD workflow for Auth Service

feature(backend, auth): created staging CI/CD workflow for Auth Service

---

apps/frontend/app/(website)/studio/features/modGPT/PromptPanel/GenerateTestCasesButton.tsx
apps/frontend/app/(website)/studio/features/modGPT/useAiService/codemodAI/useCodemodAI.tsx
apps/frontend/app/(website)/studio/features/modGPT/useAiService/useAiService.ts
apps/frontend/app/(website)/studio/main/5PaneSetup.tsx
apps/frontend/app/(website)/studio/main/PageBottomPane/TestTabsComponent.tsx
apps/frontend/app/(website)/studio/src/store/view.ts

Added a toast - indicator for test case generation

feature(studio): test generation toast

---

apps/frontend/app/(website)/studio/src/components/button/InsertExampleButton.tsx
apps/frontend/app/(website)/studio/src/store/snippets.ts
apps/frontend/app/(website)/studio/src/utils/validation/sleep.ts

change the behaviour upon clicking `example` button

feature(studio): clear tabs when example is inserted

---

.github/workflows/auth-backend-ci-cd-staging.yml

fix(auth, staging): test workflow

---

packages/codemods/npm/sort-package-json-exports/.codemodrc.json
packages/codemods/npm/sort-package-json-exports/.gitignore
packages/codemods/npm/sort-package-json-exports/LICENSE
packages/codemods/npm/sort-package-json-exports/README.md
packages/codemods/npm/sort-package-json-exports/package.json
packages/codemods/npm/sort-package-json-exports/src/index.ts
packages/codemods/npm/sort-package-json-exports/tsconfig.json
pnpm-lock.yaml

added codemod that sorts exports in package.json: CJS has higher priority over ESM

feat(codemod): npm codemod that sorts exports on package.json

---

apps/cli/package.json
apps/cli/src/commands/init.ts

Only install npm deps for JS projects.

fix(cli): deps installation

---

apps/cli/src/fetch-codemod.ts
apps/cli/src/utils/download.ts

- Introduces file-based timeout to caching logic

fix(cli): cache timeout

---

.github/workflows/codemod-backend-ci-cd-production copy 2.yml
.github/workflows/codemod-backend-ci-cd-staging.yml
.github/workflows/modgpt-backend-ci-cd-production.yml
.github/workflows/modgpt-backend-ci-cd-staging.yml
.github/workflows/run-backend-ci-cd-production.yml
.github/workflows/run-backend-ci-cd-staging.yml

feature(staging): staging workflows

---

apps/cli/package.json
packages/workflow/package.json
packages/workflow/src/engineHelpers.ts
packages/workflow/src/isWorkflowEngineFile.ts
packages/workflow/src/yaml/map.ts

Fixed incorrect return of workflow engine functions.
Adjusted detection of workflow files

fix(workflow-engine): fixed detection of engine + issue with return

---

apps/cli/src/commands/publish.ts

- Improves logic for publishing to support Windows

fix(cli): support for Windows [publish]

---

apps/cli/src/commands/init.ts
apps/cli/src/flags.ts
apps/cli/src/main.ts
apps/docs/deploying-codemods/cli.mdx
packages/utilities/src/schemata/codemod-config.ts

Run service might want to use it.

fix(cli): add back support for engine flag

---

apps/docs/guides/building-codemods/codemod2.mdx

docs: remove extra  **

---

apps/cli/package.json
packages/workflow/examples/github.ts
packages/workflow/package.json
packages/workflow/src/helpers.ts

Fixed issue glob being incorrectly resolved.
https://github.com/codemod-com/codemod/issues/1255

fix(workflow-engine): fixed glob search issue

---

apps/docs/deploying-codemods/cli.mdx

Added codemods `--logs` command to docs.

docs: add logs command

---

.github/workflows/cr.yml

This PR adds continuous releases to codemod! 
Before running the workflow, we'd have to install the [app](https://github.com/apps/pkg-pr-new)!

feat: pkg.pr.new

---

apps/backend/src/publishHandler.ts
apps/cli/build.js
apps/cli/src/commands/init.ts
apps/cli/src/commands/publish.ts
apps/cli/src/utils/detectCodemodEngine.ts
packages/codemods/typescript/use-template-literals/src/index.ts
packages/runner/src/engines/workflow.ts
packages/runner/src/runner.ts
packages/runner/src/source-code.ts

There was issue with ESM codemods: `@ast-grep/napi` cannot be bundled into codemod and it was causing error.

fix(cli,workflow-engine): adjusted esm codemods build

---

apps/cli/package.json
packages/workflow/package.json
pnpm-lock.yaml

added dependency for workflow engine

fix(cli): fix workflow engine build

---

apps/docs/guides/external-links/fastify-v3-v4.mdx
apps/docs/guides/external-links/meteor-v2-v3.mdx
apps/docs/guides/external-links/radix-reka.mdx
apps/docs/guides/introduction.mdx
apps/docs/mint.json

Adds some of the new supported migrations.

docs: update migrations

---

apps/docs/deploying-codemods/cli.mdx

Add instructions on running a codemod with a specific version.

docs: add instructions on running specific version

---

packages/codemods/ethers/v6/big-numbers/__testfixtures__/fixture1.input.ts
packages/codemods/ethers/v6/big-numbers/__testfixtures__/fixture1.output.ts
packages/codemods/ethers/v6/importing/__testfixtures__/fixture1.input.ts
packages/codemods/ethers/v6/importing/__testfixtures__/fixture1.output.ts
packages/codemods/ethers/v6/importing/__testfixtures__/fixture2.output.ts
packages/codemods/ethers/v6/providers/__testfixtures__/fixture3.output.ts
packages/codemods/ethers/v6/providers/__testfixtures__/fixture4.output.ts
packages/codemods/ethers/v6/utilities/__testfixtures__/fixture7.output.ts
packages/codemods/jasmine/5.0/handling_env-execute/__testfixtures__/fixture1.output.ts
packages/codemods/jasmine/5.0/handling_env-execute/test/test.ts
packages/codemods/jasmine/5.0/node-boot-removal/__testfixtures__/fixture1.input.ts
packages/codemods/jasmine/5.0/node-boot-removal/__testfixtures__/fixture1.output.ts
packages/codemods/meteor/v3/mongoDb-async-methods/.codemodrc.json
packages/codemods/meteor/v3/mongoDb-async-methods/src/index.ts
packages/codemods/three/r168/replace-dragcontrols-getraycaster/.codemodrc.json
packages/codemods/three/r168/replace-dragcontrols-getraycaster/src/index.ts
packages/codemods/three/r168/transform_logluvloader/__testfixtures__/fixture1.output.ts
packages/codemods/three/r168/uniforms-to-uniformarray/__testfixtures__/fixture1.output.ts

- Fixes tests that were failing due to merging faulty PRs
- Updates 2 codemods to work properly (support declared test cases)

chore: fixed codemod tests

---

apps/frontend/components/shared/pt.blocks/Quote.tsx

fix(frontend): testimonial top image height

---

apps/frontend/components/shared/pt.blocks/Quote.tsx

Fixes the image size for testimonial.
UI change. Already tested locally

fix(frontend): Fix testimonial image size

---

packages/codemods/meteor/v3/webapp-handler-renaming/package.json

The package name was using an incorrect format and breaking our CI

Fix the name of the package for meteor-3 api rename

---

apps/docs/platform/build.mdx
apps/docs/platform/run.mdx
apps/docs/platform/share.mdx

Improvements to intro sections.

docs: update intro sections

---

apps/frontend/app/auth/user.tsx

This PR fixes the issue of wrong font color in the Clerk UI component <UserProfile />. 
The issue arises because of the theme difference between the original component and the component used in codemod.
Fixed the issue by doing the said changes by going through the documentation of clerk at : [https://clerk.com/docs](url)
The documentation that supports the change done can be found at : [https://clerk.com/docs/customization/overview](url)
Fixes #1197 
Tests not required as it was a UI change.
No need to update the documentation.

BUG: Fixed the issue of wrong font color in clerk UI component

---

apps/run-service/Dockerfile

chore(backend): fixed `run-service` Dockerfile

---

apps/backend/package.json
apps/backend/src/publishHandler.test.ts
apps/backend/src/publishHandler.ts

- added codemod bucket info to the Zapier webhook

feat(backend): added bucket and uploadKey to the `Zapier` webhook

---

pnpm-lock.yaml
pnpm-workspace.yaml

Update fastify to `4.28.1` to resolve `find-my-way` vulnerabilities.

chore(deps): update fastify

---

pnpm-lock.yaml

chore(deps): update dependencies

---

apps/frontend/app/layout.tsx

Adds Apollo visitor analytics.

feat(frontend): add apollo visitor analytics

---

.changeset/funny-turkeys-search.md

Just bumping backend and auth-service

chore: Bump backend and auth-service

---

packages/codemods/ethers/v6/big-numbers/package.json
packages/codemods/ethers/v6/contracts-ambiguous-methods/package.json
packages/codemods/ethers/v6/contracts-other-methods/package.json
packages/codemods/ethers/v6/importing/package.json
packages/codemods/ethers/v6/providers/package.json
packages/codemods/ethers/v6/singatures/package.json
packages/codemods/ethers/v6/transactions/package.json
packages/codemods/ethers/v6/utilities/package.json
packages/codemods/jasmine/5.0/handling_env-execute/package.json
packages/codemods/jasmine/5.0/node-boot-removal/package.json
packages/codemods/meteor/v3/fibers-to-async-promises/package.json
packages/codemods/meteor/v3/meteor-renamed functions/package.json
packages/codemods/meteor/v3/mongoDb-async-methods/package.json
packages/codemods/meteor/v3/removedFunctions/package.json
packages/codemods/meteor/v3/webapp-handler-renaming/package.json
packages/codemods/three/r168/deactivate-to-disconnect/package.json
packages/codemods/three/r168/drag-controls-to-connect/package.json
packages/codemods/three/r168/pointer-lock-controls-to-controls-object/package.json
packages/codemods/three/r168/replace-dragcontrols-getraycaster/package.json
packages/codemods/three/r168/replace-viewport-bottom-left-with-viewportuv-flipy/package.json
packages/codemods/three/r168/replace-viewport-top-left-with-viewport-uv/package.json
packages/codemods/three/r168/transform_logluvloader/package.json
packages/codemods/three/r168/uniforms-to-uniformarray/package.json
packages/codemods/webpack/v5/json-imports-to-default-imports/package.json
packages/codemods/webpack/v5/migrate-library-target-to-library-object/package.json
packages/codemods/webpack/v5/set-target-to-false-and-update-plugins/package.json

These codemods must be flagged as private, otherwise changeset will try to publish them to NPM and errors out.

chore: Make codemod packages private

---

apps/backend/src/cron.ts

Fixes accidentally removed instatus auth webhook

fix(instatus): webhook url

---

apps/frontend/app/layout.tsx

feat(website): add google ads gtag

---

apps/frontend/app/layout.tsx

fix(website): google ads gtag

---

apps/backend/src/publishHandler.ts

Allows verified publishers override codemods

feat: Allow verified publishers override codemods

---

pnpm-lock.yaml

chore(deps): bump next.js

---

apps/backend/src/publishHandler.ts

changes passed author name schema when codemod is published

backend(update): change passed author name schema

---

apps/backend/src/publishHandler.ts

Reverts codemod-com/codemod#1424

Revert "backend(update): change passed author name schema"

---

pnpm-lock.yaml
pnpm-workspace.yaml

Downgrade nextjs to fix issue with signup

Downgrade nextjs

---

apps/frontend/app/(website)/auth/sign-in/[[...param]]/page.tsx
apps/frontend/app/(website)/studio/main/PaneLayout/LoginWarningModal.tsx
pnpm-lock.yaml
pnpm-workspace.yaml

enable withSignUp - in this mode Clerk combines sign-up and sign-in in one flow

fix: enable clerk with signup

---

apps/frontend/next.config.mjs

fix: Configure CSP headers for clerk

---

apps/frontend/middleware.ts

Adds codehike grammar urls to CSP allow list for script and connect.

chore: add codehike domain to CSP script-src portion

---

apps/frontend/middleware.ts

chore: Use explicit codehike lighter URLs for CSP

---

apps/frontend/middleware.ts
apps/frontend/next.config.mjs

This PR just removes the CSP headers from next.config that were added as an attempt to address the clerk issue

chore: remove csp headers

---

apps/frontend/middleware.ts
apps/frontend/next.config.mjs

chore: Allow more sources in CSP headers

---

apps/frontend/app/layout.tsx

fix(website): move ga4 tag higher

---

apps/frontend/app/layout.tsx

feat(frontend): add promotekit embed

---

.changeset/empty-fireants-explode.md
packages/utilities/src/package-boilerplate.ts
packages/utilities/src/registry.ts

This PR fixes the end-of-line (EOL) configuration for files in the boilerplate within the `utilities` package.  
Ensuring consistent EOL formatting helps maintain code consistency across different environments.
- Verified that EOL changes are applied correctly to affected files.
- Ensured that there were no unintended modifications to the file contents.

fix(packages/utilities): fix EOL of files in boilerplate

---

.changeset/brown-trains-look.md
packages/codemod-utils/package.json
pnpm-lock.yaml

Republish codemod-utils

---

.changeset/tasty-kiwis-rest.md
packages/codemod-utils/package.json

feat: add prepublishOnly script

---

apps/frontend/components/global/Navigation/index.tsx

remove clerk login from top nav

remove login nav

---

apps/docs/building-codemods/package-requirements.mdx
apps/docs/codemod-registry/introduction.mdx

clean up links to workflow engine. temporary fix until these pages are revamped.

clean up workflow engine links

---

.changeset/curvy-moons-wink.md
packages/codemod-utils/package.json

fix: move types export from ts file into cts file

---

apps/frontend/components/global/Navigation/index.tsx

Reverts codemod-com/codemod#1504

Revert "remove login nav"

---

apps/docs/building-codemods/package-requirements.mdx

docs(package-requirements): correct typo & indentation

---

apps/docs/building-codemods/build-package.mdx
apps/docs/building-codemods/package-requirements.mdx
apps/docs/deploying-codemods/cli.mdx
apps/docs/docs.json

update(docs): codemod learn & cli

---

.github/workflows/tag-on-version-bump.yml
Cargo.lock
Cargo.toml

chore(release): Update GitHub Actions workflow to reflect new versioning format

---

.github/workflows/tag-on-version-bump.yml
Cargo.lock
Cargo.toml

chore(release): Update version extraction regex in GitHub Actions workflow to support new format

---

Cargo.lock
crates/cli/Cargo.toml
crates/cli/src/main.rs
crates/codemod-sandbox/Cargo.toml
crates/core/Cargo.toml
crates/runners/Cargo.toml
crates/scheduler/Cargo.toml
crates/state/Cargo.toml

chore: Remove unused dependencies

---

package.json
pnpm-lock.yaml

chore(pr): remove semantic-release and related scripts from package.json

---

.changeset/dirty-panthers-film.md

fix: fix relative path detection for codemod (#1583)

---

apps/docs/cli.mdx
apps/docs/cli/cli-reference.mdx
apps/docs/cli/jssg.mdx
apps/docs/cli/workflows.mdx
apps/docs/docs.json
test-codemod/.gitignore
test-codemod/README.md
test-codemod/codemod.yaml
test-codemod/rules/config.yml
test-codemod/workflow.yaml

https://github.com/user-attachments/assets/e7449e82-8b87-45d0-991a-cfa861bec6c0

docs: Validate & fix cli docs

---

Cargo.lock
crates/cli/Cargo.toml
crates/cli/src/commands/search.rs

This refactors the improve readability and layout consistency CLI's search results table. 
> Example:
```bash
Found 93 packages:
╭──────────────────────────────────────────────┬──────────────┬──────────┬───────────┬─────────────┬─────────────────┬───────────────────────────────────────╮
│ 📦 Name                                      │ 📊 Downloads │ ⭐ Stars │ 👤 Author │ 🌐 Homepage │ 🏢 Organization │ 🔑 Keywords                           │
├──────────────────────────────────────────────┼──────────────┼──────────┼───────────┼─────────────┼─────────────────┼───────────────────────────────────────┤
│ liz/react-router/headers-export              │ 0            │ 0        │ lizkenyon │ -           │ -               │ shopify, react-router, authentication │
│ react/19/remove-forward-ref …
```

refactor(cli): improve search table layout for clarity and alignment

---

Cargo.lock
crates/cli/src/commands/jssg/run.rs
crates/cli/src/commands/jssg/testing/runner.rs
crates/codemod-sandbox/Cargo.toml
crates/codemod-sandbox/src/lib.rs
crates/codemod-sandbox/src/sandbox/engine/config.rs
crates/codemod-sandbox/src/sandbox/engine/execution_engine.rs
crates/codemod-sandbox/src/sandbox/engine/quickjs_adapters.rs
crates/codemod-sandbox/src/sandbox/loaders/mod.rs
crates/codemod-sandbox/src/sandbox/mod.rs
crates/codemod-sandbox/src/sandbox/resolvers/mod.rs
crates/codemod-sandbox/src/sandbox/resolvers/oxc_resolver.rs
crates/codemod-sandbox/src/utils/mod.rs
crates/codemod-sandbox/src/utils/project_discovery.rs
crates/core/src/engine.rs

feat(codemod-sandbox): integrate OxcResolver for module resolution

---

crates/cli/src/commands/login.rs

feat(cli): add API key authentication to login command

---

crates/cli/src/commands/publish.rs

This fixes the issue of package name validation when package name is scoped.

fix: fix package name validation in publish command to support scoped packages

---

crates/core/src/registry.rs

fix: fix package specification parsing to handle scoped packages correctly

---

crates/cli/src/commands/publish.rs
crates/cli/src/commands/workflow/validate.rs
crates/core/src/engine.rs
crates/core/src/utils.rs
crates/core/tests/utils_tests.rs

This PR adds validation to ensure that the `config_file` and `js_file` paths specified in `workflow.yaml` actually exist on the filesystem.
- Ran `cargo test` and verified all test cases pass.
- Test manually

feat: validate config_file and js_file existence in workflow.yaml steps [CDMD-4290]

---

crates/core/src/engine.rs
rust-toolchain.toml

fix: Fix ast-grep yaml codemod target path resolution bug

---

crates/cli/src/commands/init.rs
crates/cli/src/templates/astgrep-yaml/workflow.yaml
crates/cli/src/templates/js-astgrep/workflow.yaml

fix: Update workflow templates to use dynamic language and improve next steps messaging

---

action.yml
biome.json

fix(ci): lint

---

apps/docs/cli/cli-reference.mdx
crates/cli/src/commands/init.rs
crates/cli/src/templates/hybrid/workflow.yaml

chore(cli): hide shell & yaml codemods

---

crates/core/src/execution.rs

fix(execution): respect gitignore

---

crates/core/src/engine.rs
crates/models/src/variable.rs
crates/scheduler/src/lib.rs

feat(engine): dot notation resolution for state paths

---

Cargo.lock
Cargo.toml
crates/cli/Cargo.toml
crates/cli/src/workflow_runner.rs
crates/core/src/engine.rs
crates/core/src/registry.rs
crates/core/tests/engine_tests.rs
crates/scheduler/src/lib.rs

This adds:
- hashing json of matrix input to correlate tasks across multiple runs changing state
- replace openssl with rusttls
- improve waiting for task completions. using notify instead of polling

feat: handle matrix task matching based on matrix input values

---

crates/cli/src/commands/jssg/run.rs
crates/cli/src/commands/run.rs
crates/cli/src/main.rs

Things done in this PR:
- Converted verbose and disable analytics into a single global argument and fixed the issue with using `-‍‍-` before calling them
- Fixed the param issue in the jssg run and run commands
- Passed the `--no-telemetry` argument to the legacy command

fix: fix disable analytic flag bug

---

crates/cli/src/templates/astgrep-yaml/workflow.yaml
crates/cli/src/templates/codemod.yaml
crates/cli/src/templates/hybrid/workflow.yaml
crates/cli/src/templates/js-astgrep/workflow.yaml
crates/cli/src/templates/shell/workflow.yaml

chore(workflows): update yaml templates to include schema references and remove deprecated fields

---

crates/cli/src/templates/js-astgrep/package.json
crates/cli/src/templates/js-astgrep/scripts/codemod.go.ts
crates/cli/src/templates/js-astgrep/scripts/codemod.java.ts
crates/cli/src/templates/js-astgrep/scripts/codemod.py.ts
crates/cli/src/templates/js-astgrep/scripts/codemod.rs.ts
crates/cli/src/templates/js-astgrep/scripts/codemod.ts.ts

chore(templates): use the latest version of jssg types in templates
