apps/registry/codemods/typescript/remove-public-modifier/.mocharc.json
apps/registry/codemods/typescript/remove-public-modifier/README.md
apps/registry/codemods/typescript/remove-public-modifier/config.json
apps/registry/codemods/typescript/remove-public-modifier/index.d.ts
apps/registry/codemods/typescript/remove-public-modifier/package.json
apps/registry/codemods/typescript/remove-public-modifier/src/index.ts
apps/registry/codemods/typescript/remove-public-modifier/test/test.ts
apps/registry/codemods/typescript/remove-public-modifier/tsconfig.json
pnpm-lock.yaml

Adds a TS Codemod - Remove Public Modifier

Registry: TS Codemod - Remove Public Modifier

---

apps/registry/codemods/react-router/4/replace-location-query/.mocharc.json
apps/registry/codemods/react-router/4/replace-location-query/README.md
apps/registry/codemods/react-router/4/replace-location-query/config.json
apps/registry/codemods/react-router/4/replace-location-query/index.d.ts
apps/registry/codemods/react-router/4/replace-location-query/package.json
apps/registry/codemods/react-router/4/replace-location-query/src/index.ts
apps/registry/codemods/react-router/4/replace-location-query/test/test.ts
apps/registry/codemods/react-router/4/replace-location-query/tsconfig.json
pnpm-lock.yaml

- Adds one codemod for migrating React Router from v3 to v4. This codemod replaces instances of `location.query` with `parse(location.search)`, where `parse` is a function imported from `query-string`.

CDMD-2459 [React Router Codemod] Replace location.query

---

apps/cli/src/downloadCodemod.ts
apps/cli/src/handleListCliCommand.ts
apps/cli/src/printer.ts
apps/cli/src/runner.ts
apps/cli/src/schemata/codemodConfigSchema.ts
pnpm-lock.yaml

- Does not show that codemod is executing before actual download happens.
- Now instead of showing 403 request error from axios, we show clear error saying that codemod wasn't found and show user a list of commands.

feat: execute list command on codemod not found (CDMD-2590)

---

apps/registry/codemods/react/19/use-context-hook/README.md
apps/registry/codemods/react/19/use-context-hook/config.json
apps/registry/codemods/react/19/use-context-hook/index.d.ts
apps/registry/codemods/react/19/use-context-hook/package.json
apps/registry/codemods/react/19/use-context-hook/src/index.ts
apps/registry/codemods/react/19/use-context-hook/test/test.ts
apps/registry/codemods/react/19/use-context-hook/tsconfig.json
pnpm-lock.yaml

This PR adds a codemod that would migrate context usages in React v19 to using `use` hook.

feat: React Compiler useContext codemod (CDMD-2578)

---

apps/cli/src/handlePublishCliCommand.ts
apps/studio-backend/src/publishHandler.ts
apps/studio/src/utils/download.ts

Currently, we create `config.json` on the spot when `codemod publish` is called.

CDMD-2624 part 1: Use the existing config.json on `codemod publish` command

---

apps/cli/package.json
apps/cli/src/codemod.ts
apps/cli/src/downloadCodemod.ts
apps/cli/src/runAstgrepCodemod.ts
apps/cli/src/runCodemod.ts
apps/cli/src/schemata/codemodConfigSchema.ts
apps/docs/mint.json
pnpm-lock.yaml

**Summary**
- In commit 1, adding no-op ast-grep engine to codemod cli 
- In commit 2, added implementation of ast-grep engine to cli 
**Testing**
I put the following code in a file called abc.js in folder `/Users/harshgupta/Desktop/src/codemod/apps/cli/ast/abc.js`
```
import { A, B, C } from './barrel';
function Component() {
const [name, setName] = useState < string > ('React')
}
``` 
In directory `/Users/harshgupta/.codemod`, chose a random folder `XG6X5ceI2dzkLW7CoBI0aD3W_7Q`, and updated it's config.json to have engine `ast-grep`. 
config.json after update 
```
"schemaVersion":"1.0.0","engine":"ast-grep","arguments":[],"name":"cal.com/app-directory-boilerplate-calcom"}
```
Also added a file called rule.yaml in `XG6X5ceI2dzkLW7CoBI0aD3W_7Q` and content of yaml file was 
```
id: …
```

Add ast-grep as an engine 

---

apps/cli/src/executeMainThread.ts

this causes JSON.parse() in VSCE to fail to load registry codemods
e.g.,
```
const childProcess = spawn(
CODEMOD_ENGINE_NODE_COMMAND,
["list", "--json", "--short"],
{
stdio: "pipe",
shell: true,
detached: false,
},
);
const codemodListJSON = await streamToString(childProcess.stdout);
const codemodListOrError = codemodNamesCodec.decode(
JSON.parse(codemodListJSON),
);
```

[VSCE, CLI] fix: `--json` option is not applied to command list - CDMD-2702

---

apps/backend/package.json
apps/backend/src/schemata/query.ts
apps/backend/src/server.ts
apps/cli/src/apis.ts
apps/cli/src/executeMainThread.ts
apps/cli/src/handleListCliCommand.ts
pnpm-lock.yaml

- Adds `codemod search` command that behaves similarly to `codemod list` but allows perfoming fuzzy-find by name on codemod list
- Changes `codemod list` to work exactly the same as search and those two commands to work similarly

[CLI, Backend] feat: Add fuzzy-search command and make it interchangeable by list (CDMD-2768)

---

apps/cli/src/handlePublishCliCommand.ts

- Removes double error printing when publish endpoint fails to respond with positive status code
- Removes redundant variable
- Removes `package.json` related logic as we no longer rely on this file
This PR does not introduce any changes related to error printing, because the issue described in the original ticket that is related to this PR has been fixed in the progress of migrating our public registry.

[CLI] fix: Small fixes in code (CDMD-2769)

---

apps/backend/src/publishHandler.test.ts
apps/backend/src/publishHandler.ts
apps/cli/src/downloadCodemod.ts
apps/cli/src/handlePublishCliCommand.ts

Until now, we only supported publishing of js codemods. We want to allow publishing for all the engines we support, since publishing is now the only way to get codemods into the registry.

[CLI, Backend] feat: allow publishing codemods of any engine (CDMD-2826)

---

packages/codemods/react/19/remove-forward-ref/src/index.ts
packages/codemods/react/19/remove-forward-ref/test/test.ts

-  should not remove type imports
- should handle case where generic params are not used, but wrapped function is typed
- should handle arg names

[CODEMOD: FN, FP]: remove 2 FN, 1 FP

---

apps/cli/src/buildCodemodOptions.ts
apps/cli/src/codemod.ts
apps/cli/src/downloadCodemod.ts
apps/cli/src/executeWorkerThread.ts
apps/cli/src/handleInstallDependencies.ts
apps/cli/src/handlePublishCliCommand.ts
apps/cli/src/mainThreadMessages.ts
apps/cli/src/runAstgrepCodemod.ts
apps/cli/src/runCodemod.ts
apps/cli/src/safeArgumentRecord.ts
apps/cli/src/schemata/argumentRecordSchema.ts
apps/cli/src/workerThreadManager.ts
packages/utilities/src/schemata/codemodConfigSchema.ts

This PR makes it so that ast-grep codemods are executed in the same fashion as our adopted engines. This allows proper messaging like `Processed X files out of Y` and in general makes the execution flow more predictable.

[CLI] feat: ast-grep compatible implementation

---

apps/backend/package.json
apps/backend/src/server.ts

- Removed  null `useCaseCategory` values from filters.
- Bumped version to 0.0.51

[Backend, Registry] chore: Removed null `useCaseCategory` values from filters

---

apps/cli/src/apis.ts
apps/cli/src/executeMainThread.ts
apps/cli/src/handleListCliCommand.ts
apps/cli/src/messages.ts
apps/cli/src/printer.ts
apps/vsce/src/components/engineService.ts
packages/utilities/src/index.ts
packages/utilities/src/schemata/codemodListResponse.ts

Sample output:
```json
{
"kind": "codemodList",
"codemods": [
{
"name": "rename-data-to-data-legacy",
"engine": "jscodeshift",
"author": "alexbit-codemod",
"tags": []
},
{
"name": "replace-from-global-id-with-get-object-id",
"engine": "jscodeshift",
"author": "sibelius",
"tags": []
},
{
"name": "next-i18next/copy-keys",
"engine": "filemod",
"author": "codemod.com",
"tags": []
},
{
"name": "react/prop-types-typescript",
"engine": "jscodeshift",
"author": "codemod.com",
"tags": ["react"]
},
{
"name": "react-redux/0/add-state-type",
"engine": "jscodeshift",
"author": "codemod.com",
"tags": []
},
{
"name": "generate-url-patterns",
"engine": "filemod",
"author": "codemod.com",
"tags": []
}
]
}
```

[CLI] fix: remove short arg, add arguments to the output (CDMD-3019)

---

apps/vsce/src/components/webview/MainProvider.ts
apps/vsce/src/extension.ts
apps/vsce/src/selectors/selectCodemodTree.ts
apps/vsce/webview/src/campaignManager/App.tsx
apps/vsce/webview/src/codemodList/CodemodNodeRenderer/Codemod.tsx

Previously, we had info about arguments via config.json files and, using this info, we conditionally showed UI for codemod arguments. We no longer store config.json files locally, so I am commenting out all code related to Codemod Arguments and drop the support for it. In the future, we can create some backend API that returns arguments related information and use this in VSCE to show UI for codemod arguments.

[VSCE] Comment out business logic for Codemod Arguments - CDMD-3015

---

apps/cli/src/buildCodemodOptions.ts
apps/cli/src/buildSurfaceAgnosticJob.ts
apps/cli/src/codemod.ts
apps/cli/src/downloadCodemod.ts
apps/cli/src/repositoryConfiguration.ts
apps/cli/src/runner.ts
apps/cli/src/safeArgumentRecord.ts
apps/cli/src/schemata/codemodSettingsSchema.ts
apps/cli/test/runner.test.ts

- Adjusts logical distribution of sourced and registry codemod runs to "standalone" and "package", because we can infer data from codemod package if it's a valid codemod directory.
- Adds a check for required args and a corresponding message:

[CLI] feat: add check for required args (CDMD-3041)

---

apps/backend/package.json
apps/backend/prisma/migrations/20240405180019_s3_data_format/migration.sql
apps/backend/prisma/schema.prisma
apps/backend/prisma/seed.ts
apps/backend/src/customHandler.ts
apps/backend/src/handlers/getCodemodDownloadLink.ts
apps/backend/src/handlers/getCodemodsListHandler.ts
apps/backend/src/handlers/revokeTokenHandler.ts
apps/backend/src/handlers/validationHandler.ts
apps/backend/src/publishHandler.ts
apps/backend/src/server.ts
apps/backend/src/services/codemodService.ts
apps/cli/src/apis.ts
apps/cli/src/downloadCodemod.ts
apps/cli/src/handlePublishCliCommand.ts
apps/cli/src/handleWhoAmICommand.ts
apps/cli/src/utils.ts
pnpm-lock.yaml

NOTE: This PR is stacked on top of #293 
Changes:
- Adjusts how we store s3 url data in the database for improved flexibility
- Introduces s3 url signing functionality to provide access to private codemods for authorized users
- Minor customhandler wrapper method injection/usage refactoring:
- getAccessTokenOrThrow -> getAccessToken
- add `getClerkUserData` method

[Backend, CLI] feat: orgs part 2 (CDMD-3024, CDMD-2695, CDMD-2760, CDMD-2761, CDMD-2824)

---

apps/backend/esbuild.config.js
apps/backend/package.json
apps/backend/src/publishHandler.ts
apps/cli/build.js
apps/cli/package.json
apps/cli/scripts/postinstall.js
apps/cli/src/downloadCodemod.ts
apps/cli/src/executeMainThread.ts
apps/cli/src/handleLoginCliCommand.ts
apps/cli/src/handleLogoutCliCommand.ts
apps/cli/src/handlePublishCliCommand.ts
apps/cli/src/utils.ts
apps/docs/codemod-registry/publishing-codemods.mdx
biome.json
packages/filemod/src/unifiedFileSystem.test.ts
packages/utilities/src/package-boilerplate.ts
packages/utilities/src/registry.ts
pnpm-lock.yaml

- Adds keychain impl to support writing token to system encrypted storage
- adds post-install script to install esbuild globally for `codemod build` command to work
- fixes esm/cjs issues in utils package
- fixes backend build issue (hopefully)
- adjusts documentation just a bit
- allows changing privacy of the codemod

[CLI, Backend, Utils] feat: keychain implementation, post-install script (CDMD-2464)

---

apps/backend/package.json
apps/backend/prisma/migrations/20240411123904_cascade_delete_versions/migration.sql
apps/backend/prisma/schema.prisma
apps/backend/src/publishHandler.test.ts
apps/backend/src/publishHandler.ts
apps/backend/src/schemata/schema.ts
apps/backend/src/server.ts
apps/backend/src/unpublishHandler.ts
apps/cli/package.json
apps/cli/src/apis.ts
apps/cli/src/executeMainThread.ts
apps/cli/src/handleInstallDependencies.ts
apps/cli/src/handleListCliCommand.ts
apps/cli/src/handlePublishCliCommand.ts
apps/cli/src/handleUnpublishCliCommand.ts
packages/utilities/src/schemata/codemodConfigSchema.ts

- `codemod unpublish` logic CLI + backend impl
- eliminate code repetition in `executeMainThread` file
- Delete codemod versions with cascade behaviour, create migration for that
- Bump versions
- Minor refactoring to correspond to our development practices

[CLI, Backend] feat: `codemod unpublish` (CDMD-2667)

---

apps/backend/package.json
apps/backend/src/handlers/getCodemodsListHandler.ts
apps/backend/src/services/codemodService.ts
apps/cli/package.json
apps/cli/src/buildCodemodOptions.ts
apps/cli/src/downloadCodemod.ts
apps/cli/src/executeWorkerThread.ts
apps/cli/src/handleInstallDependencies.ts
apps/cli/src/handleListCliCommand.ts
apps/cli/src/handleLoginCliCommand.ts
apps/cli/src/handlePublishCliCommand.ts
apps/cli/src/handleUnpublishCliCommand.ts
apps/cli/src/messages.ts
apps/cli/src/printer.ts
apps/cli/src/runCodemod.ts
apps/cli/src/workerThreadManager.ts
apps/cli/src/workerThreadMessages.ts
packages/utilities/src/schemata/codemodListResponse.ts
pnpm-lock.yaml

- Fixes empty prints
- Fixes wrong total files
- Introduces dedicated loader library instead of from-scratch solution
- Fix codemod list sorting (perform it on backend, perform it via fuzzy-find library by score if search is provided, otherwise alphabetically)
- Minor fixes, such as using types from utilities shared package and dead code removal

[CLI, Backend] fix: empty prints, wrong total files, dedicated loader library, fix codemod list sorting

---

apps/cli/src/commands/init.ts
apps/cli/src/commands/learn.ts
apps/cli/src/commands/list.ts
apps/cli/src/commands/publish.ts
apps/cli/src/commands/run.ts
apps/cli/src/commands/unpublish.ts
apps/cli/src/commands/whoami.ts
apps/cli/src/downloadCodemod.ts
apps/cli/src/handleInstallDependencies.ts
packages/printer/src/printer.ts
packages/utilities/src/index.ts

- Removes redundant spaces in chalk prints
- Unifies chalk usage to prefer comma notations for joined strings instead of template literals, where possible, for readability reasons.

[Printer, CLI] fix: text formatting

---

packages/codemods/next/13/replace-next-router/src/index.ts
packages/codemods/next/13/replace-next-router/test/test.ts

bug fix
inject of imports before 'use client'
inject of imports …

Fixed codemod injection of imports before 'use client'

---

apps/cli/package.json
pnpm-lock.yaml

ensure that externalized deps are in "dependencies" not in "devDependencies" so they are included to the CLI installation via `pnpm add --global`

Fix CLI build

---

apps/cli/package.json
apps/cli/src/fileDownloadService.ts
apps/frontend/app/(website)/blog/tag/[tag]/page.tsx

- discard cache if there is never file in the S3 bucket
- fixes the issue where new versions of codemod were ignored with cache option enabled

fix: fix download service

---

apps/frontend/components/templates/CodemodPage/CodemodPageUI.tsx
apps/frontend/sanity/schemas/objects/automationVersion.ts

Renames "Total time saved" to "Total runs".

[registry] rename time saved to total runs

---

apps/cli/src/commands/build.ts

- makes entry point glob pattern more strict to avoid FP matches such as `index.test.ts`. 
- improves error message

fix: strict entry point pattern

---

apps/backend/package.json
apps/backend/src/services/codemodService.ts

- replaced `framework` field with `frameworks` so we have all frameworks related to this `codemod` in this field
- bumped version to 0.0.92

[Backend]: replaced `framework` field with `frameworks` (CDMD-3235)

---

apps/cli/src/commands/init.ts
apps/cli/src/commands/publish.ts
apps/cli/src/executeMainThread.ts
apps/frontend/app/(website)/studio/src/utils/download.ts
packages/utilities/src/index.ts
packages/utilities/src/package-boilerplate.ts

Upon merging this PR, #506 can be closed. (@DmytroHryshyn)
- `codemod init` questions are adjusted if main file/folder path is provided
- When user tries to run `codemod publish` on a directory, we will ask him to provide a path to the main file in that directory and use this directory as a default path to run `codemod init` on.
- When user tries to run it on a concrete file, we do the same, but get the default directory based on where this file is located.

[CLI, utilities] feat: init during publish (CDMD-3283)

---

apps/cli/src/buildCodemodOptions.ts
apps/frontend/app/(website)/registry/[codemod]/page.tsx
apps/frontend/app/(website)/studio/src/store/zustand/CFS/index.ts
apps/frontend/app/(website)/studio/src/store/zustand/codemodOutput.ts
apps/frontend/app/(website)/studio/src/store/zustand/log.ts
apps/frontend/app/(website)/studio/src/store/zustand/mod.ts
apps/frontend/app/(website)/studio/src/store/zustand/snippets.ts
apps/frontend/app/(website)/studio/src/store/zustand/view.ts
apps/frontend/app/api/apply-to-job/route.ts
apps/frontend/app/api/contact-form/route.ts
apps/frontend/app/api/newsletter-form/route.ts
apps/frontend/app/api/og/route.tsx
apps/frontend/app/sitemap.ts
apps/frontend/config.ts
apps/frontend/data/codemod/loaders.ts
apps/frontend/data/sanity/resolveSanityRouteMetadata.tsx
apps/frontend/data/sanity/token.ts
apps/frontend/env.ts
apps/frontend/sanity.cli.ts
packages/runner/src/schemata/codemodSettingsSchema.ts
pnpm-lock.yaml

- fix warning telling to `import { create } from 'zustand'` instead of using default export
- fix using env variables from `process.env` instead of using validation library

[Frontend] fix: build warnings and env validation

---

apps/cli/package.json
apps/cli/src/buildOptions.ts
apps/cli/src/executeMainThread.ts
apps/cli/src/safeArgumentRecord.ts
packages/codemods/react/19/remove-forward-ref/.codemodrc.json
packages/utilities/src/index.ts
packages/utilities/src/schemata/argumentRecordSchema.ts
packages/utilities/src/schemata/codemodConfigSchema.ts

Provided the following args are used:
This is the console output when they are missing:
Stacked on top of #544

[CLI] feat: support enum args and multiple arg types

---

apps/cli/src/commands/run.ts
apps/cli/src/safeArgumentRecord.ts

- fixed array of kinds validation
- added logic that allows user to provide missing args manually
Example:
giving the following arguments configuration:
and provided user input shown on below screenshot, revalidation will happen and print all the errors if any, otherwise continue codemod execution:

[CLI] feat: ask user to provide missing args and perform re-validation (CDMD-3343)

---

apps/cli/package.json
apps/cli/src/buildEngineOptions.ts
apps/cli/src/commands/run.ts
apps/cli/src/executeWorkerThread.ts
packages/printer/package.json
packages/printer/src/schemata/mainThreadMessages.ts
packages/runner/package.json
packages/runner/src/runCodemod.ts
packages/runner/src/runJscodeshiftCodemod.ts
packages/runner/src/runner.ts
packages/runner/src/workerThreadManager.ts
packages/runner/test/runJscodeshiftCodemod.test.ts
packages/utilities/src/index.ts
packages/utilities/src/schemata/engineOptionsSchema.ts

- adds ability to pass jscodeshift options. for now only `parser` option, as other options like `--dry` or `--verbose` are controlled by the runner, not the engine itself.

 Feat/support engine native options CDMD-3350

---

apps/cli/package.json
apps/cli/src/commands/run.ts

Examples:
If `git status --porcelain` yields no diff, then no prompt is printed.

[CLI] feat: check file tree before running (CDMD-3333, CDMD-3322)

---

apps/cli/src/executeMainThread.ts

Previously:
Now:
Previously, the process wouldn't exit if the error was thrown. Fixed in this PR.

[CLI] fix: empty unpublish weird err msg

---

apps/cli/src/commands/init.ts
packages/utilities/src/package-boilerplate.ts

- Adds test fixtures to `codemod init` output
- Fixes text issues upon `codemod init` command finished execution

[CLI] feat: add test fixtures to init output (CDMD-3334)

---

apps/cli/src/commands/learn.ts

Previously studio would break if path contained `$` or `^` symbols. Fixed in this PR.

[CLI] fix: studio broken learn (CDMD-3323)

---

apps/task-manager/package.json
apps/task-manager/src/services/GithubProvider.ts

[runner] Using codemod name from user on github branch name can throw errors

---

apps/backend/package.json
apps/backend/src/server.ts
apps/cli/package.json
apps/cli/src/apis.ts
apps/cli/src/commands/run.ts
apps/cli/src/downloadCodemod.ts
apps/cli/src/fileDownloadService.ts

- Fixed access token not being passed to an endpoint that retrieves codemod download URI
- Fixed wrong logic for assembling user allowed namespaces in the same endpoint
- Fixed bad indentation in download error
- Improved cache disabled/enabled messages with reasons given to the user where appropriate
- Improved execution flow in `downloadCodemod.ts` to achieve better error messages

[CLI, Backend] fix: resolve publishing/downloading issues

---

packages/codemods/react/prop-types-typescript/.codemodrc.json

Fixes missing git meta for the React prop-types-typescript codemod

[codemods] fix prop-types-typescript git meta

---

apps/cli/build.js
apps/cli/package.json
pnpm-lock.yaml

napi should be in cli dependencies, otherwise it won't get installed and won't be available in runtime
i also did not understand why we have workflow externalized. i guess it's fine to include it in the bundle. size change is 0,1 mb or similar

[CLI] fix: deps issue

---

apps/cli/src/buildCodemodOptions.ts
apps/cli/src/commands/publish.ts
apps/cli/src/commands/run.ts
apps/cli/src/downloadCodemod.ts
apps/cli/src/utils.ts
packages/runner/src/codemod.ts
packages/utilities/src/schemata/codemodConfigSchema.ts
pnpm-lock.yaml

- now prints version of codemod that is being run
- always build the codemod before publishing
- always build the codemod before running
- fix semver validation logic

[CLI] feat: print codemod version and always build the codemod

---

.gitignore
apps/cli/package.json
apps/cli/src/buildOptions.ts
apps/cli/src/commands/run.ts
apps/cli/src/executeMainThread.ts
apps/cli/src/handleInstallDependencies.ts
apps/cli/src/utils.ts
apps/docs/deploying-codemods/cli.mdx
packages/runner/src/runCodemod.ts
packages/runner/src/schemata/codemodSettingsSchema.ts
packages/runner/src/schemata/flowSettingsSchema.ts
packages/utilities/src/functions/projectRoot.ts
packages/utilities/src/index.ts

- Now showing the target that codemod is going to run on in the run summary
- Codemod include and exclude patterns became smarter. If they are provided by user through options or through codemod config options, include patterns take priority. If they are determined by engine or set by ast-grep configuration, exclude patterns provided by user through arguments will take over. Depending on which one has the priority, the other list will be filtered to not contain patterns from the prioritized list.
- Added `dist`, `build`, `.next` folders to default excluded patterns
- Removed .d.ts files from ignored by default
- Now we assume that path is a directory and should be formatted as `**/path/**/*.*` glob pattern if user supplies it with a trailing slash
- Now supporting specifying target path …

[CLI] feat: smarter include/exclude options (CDMD-3450, CDMD-3451, CDMD-3462, CDMD-3470, CDMD-3448)

---

apps/cli/package.json
apps/cli/src/executeMainThread.ts

Because our CLI has no dedicated command for running, it enters running command execution before it can reach the version console.log logic. It is also impossible to access yargs argv twice, so instead we are just checking for presence of the version flag manually without yargs help.

[CLI] fix: version

---

apps/cli/package.json
apps/cli/src/commands/run.ts
apps/cli/src/downloadCodemod.ts

Fixes a bug where CLI would throw weird error with no clear description if codemod was not found.

[CLI] fix: improve not found messages

---

apps/vsce/webview/src/CodemodEngineNodeNotFound/index.tsx
apps/vsce/webview/src/CodemodEngineNodeNotFound/style.module.css
apps/vsce/webview/src/LoadingRegistry/index.tsx
apps/vsce/webview/src/LoadingRegistry/style.module.css

[vsce] fix styles of loading screen and cli not found screen

---

apps/cli/package.json
packages/runner/package.json
packages/runner/src/runCodemod.ts
packages/runner/src/runner.ts

- supports tracking of `modifiedFilePaths` for recipes; this is needed because deps installation logic depends on modified path to find affected package jsons;

CDMD-3477 Fix/deps install

---

packages/codemods/react/19/replace-reactdom-render/.codemodrc.json
packages/codemods/react/19/replace-reactdom-render/README.md
packages/codemods/react/19/replace-reactdom-render/__testfixtures__/unmount.input.js
packages/codemods/react/19/replace-reactdom-render/__testfixtures__/unmount.output.js
packages/codemods/react/19/replace-reactdom-render/src/index.ts
packages/codemods/react/19/replace-reactdom-render/test/test.ts

- support replacement of `reactDom. unmountComponentAtNode`
- refactor codemod

[Registry] react/19/replace-reactdom-render support unmountComponentAtNode

---

apps/frontend/app/(website)/registry/[codemod]/page.tsx
apps/frontend/components/templates/CodemodPage/parts/Code.tsx

Fix registry code examples overflow issue: 
Before: 
After:

fix overflow issue for code blocks

---

apps/cli/src/commands/run.ts

Bug fix
When the target folder is not tracked by git and the user selects 'No' in the prompt indicating that the codemod changes …

[CLI] fix: ensure process exits when user selects 'No' in git tracking prompt

---

.github/workflows/build.yml
apps/backend/package.json
apps/backend/src/publishHandler.test.ts
apps/backend/src/publishHandler.ts
apps/backend/src/unpublishHandler.ts
apps/frontend/app/(website)/auth/layout.tsx
apps/frontend/app/(website)/page.tsx
apps/frontend/app/(website)/registry/[codemod]/page.tsx
apps/frontend/app/(website)/studio/page.tsx
apps/frontend/app/api/revalidate-tag/route.ts
apps/frontend/app/context/AuthProvider.tsx
apps/frontend/app/layout.tsx
apps/frontend/components/global/Navigation/DesktopNavigation.tsx
pnpm-lock.yaml

- removes clerk AuthProvider from global layout. (clerk auth provider uses `headers()` internally, which makes all pages dynamic);
- adds revalidate-tag endpoint
- fixes codemod caching strategy
- triggers revalidation of both page and tag on publish/unpublish

[Registry-www]: Fix SSG

---

apps/cli/src/commands/run.ts
packages/runner/src/runCodemod.ts
packages/runner/src/runRepomod.ts

- fixes paths generation for filemod (only does it once now and makes sure they are the same as our CLI generates)
- fixes execution progress bar not going up to 100% by awaiting onSuccess() method (it gives time for progress bar update to go through, it seems like this operation is being executed on process.nextTick() or something similar, basically it's not a sync operation apparently)
- excluded patterns color is now yellow instead of red as per request from Jacob Paris

[CLI, Runner] fix: filemod paths generation, execution progress bar cutoff, excluded patterns color (CDMD-3635)

---

packages/codemods/typescript/use-template-literals/src/index.ts

feature: codemod: typescript: remove useless conversion to string

---

packages/runner/src/runJscodeshiftCodemod.ts

We were trying to use jscodeshift raw when adapter is needed. It produced parsing errors.

[CLI] fix: remove redundant errors (CDMD-3353)

---

apps/frontend/app/(website)/studio/main/PaneLayout/tabsData.tsx

The intention of this PR is to change the "ModGPT" tab in the studio to "Assistant".

[studio] rename modgpt tab to assistant

---

package.json
pnpm-lock.yaml

Automate changelog releases with semantic-release and commitizen.
Moving forward, please commit using `npm run commit` and populate the fields `commitizen` prompts accurately for correct releases.

build(release): add semantic-release & commitizen

---

apps/cli/package.json
packages/runner/src/runCodemod.ts
packages/workflow/package.json
packages/workflow/src/astGrep/astGrep.ts

1. When directory is provided in `.gitignore` - codemod doesn't take it into account and doesn't ignore files inside.
2. When file with unknown extension is met for ast-grep in workflow engine - show warning.

Gitignore fix, unsupported file extension fix

---

apps/cli/package.json
packages/workflow/package.json
packages/workflow/src/fs/move.ts

Use posix for manipulating path in imports of JS files on windows, otherwise imports are getting broken

fix(workflow engine): fix import paths when moving files on windows

---

apps/backend/src/publishHandler.ts
apps/cli/package.json
apps/cli/src/api.ts
apps/cli/src/commands/publish.ts
biome.json
scripts/batchPublish.ts
turbo.json

- include `packages` into biome.json formatter coverage
- bugfixes:
- during recipe publishing, we attempted to build the codemod executable. recipe does not have one.
- codemod list was requesting auth to view all the codemods by error (apparently was pushed with another PR)
- any codemod path that included `temp` would get removed, when we only need to remove the ones that were created in the actual `temp` directory under `.codemod`

fix(cli): post-refactoring logic fixes

---

apps/frontend/app/(website)/studio/main/ASTViewer/utils.ts

It appeared that children can be a simple object instead of an array. In this PR we assure that every child is an array

six(studio): ast-tree children generation always set to be arrays

---

apps/backend/package.json
apps/backend/src/unpublishHandler.ts
apps/cli/package.json
apps/cli/src/commands/unpublish.ts
apps/cli/src/install-dependencies.ts
packages/utilities/package.json
packages/utilities/src/functions/formatting.ts
packages/utilities/src/schemata/codemod-config.ts

fix(cli,backend): patch a bug that incorrectly extracts codemod name and version

---

apps/auth-service/package.json
apps/auth-service/src/server.ts
apps/backend/package.json
apps/backend/src/publishHandler.ts
apps/backend/src/unpublishHandler.ts
apps/cli/package.json
apps/cli/src/commands/init.ts

- Patches logic which used to set namespace to username unconditionally
- Brings back `npm install` logic to `codemod init` as it was removed in previous PRs due to assuming it was working incorrectly. Article written by one of our users has proven this wrong and it seemed like users actually want this behaviour.

fix(cli, backend): patch for namespace logic & return codemod dep installation

---

apps/cli/package.json
apps/cli/src/commands/run.ts
apps/cli/src/worker.ts
packages/printer/src/schemata/main-thread.ts
packages/runner/src/runner.ts
packages/runner/src/schemata/flow-settings.ts
packages/runner/src/worker-manager.ts

- Sets target as `dirname(target)` and does `include = [...include, basename(target)` when target is a file.
- Passes entire codemod source through worker thread message to avoid constructing new annonymous function that loses the scope. Previously I've done that in attempt to avoid calling`getTransformer` on every processed file, however I overlooked that this optimization would cause this bug and turn out to be inefficient, since calling `new Function()` is probably way heavier than just extracting the transformer. The architecture can be improved here in some way, for example passing the transformer *name* with the message, but for now let's leave it bare min so that it works as before.

fix(cli): allow targeting single file, preserve source scope

---

apps/run-service/src/server.ts
apps/run-service/src/services/Redis.ts
packages/utilities/src/schemata/github-run.ts

Permanently saving output for codemod runs

feat(run-service): added ability to save output of codemod runs permanently

---

apps/cli/src/commands/run.ts
apps/cli/src/fetch-codemod.ts
apps/cli/src/flags.ts
apps/vsce/package.json
apps/vsce/src/components/buildArguments.ts
packages/runner/src/schemata/flow-settings.ts
packages/workflow/package.json
packages/workflow/src/codemod.ts

Added no-interactive flag for running cli (for example do not ask which recipes to run)

feat(cli): add no-interactive flag

---

packages/codemods/react/19/replace-default-props/__testfixtures__/partial-default-props.input.tsx
packages/codemods/react/19/replace-default-props/__testfixtures__/partial-default-props.output.tsx
packages/codemods/react/19/replace-default-props/src/index.ts
packages/codemods/react/19/replace-default-props/test/test.ts

It seems thats `replace-default-props` only works when all props are defaulted but when a prop is required it won't be included in `defaultProps`. This PR attempts to fix the issue by skipping props that don't have defaults.
Example error that we were seeing:
```
Error: undefined does not match field "right": Expression of type AssignmentPattern
❯ addParam ../../../../../node_modules/.pnpm/ast-types@0.16.1/node_modules/ast-types/src/types.ts:599:17
❯ ../../../../../node_modules/.pnpm/ast-types@0.16.1/node_modules/ast-types/src/types.ts:627:13
❯ Function.builder [as assignmentPattern] ../../../../../node_modules/.pnpm/ast-types@0.16.1/node_modules/ast-types/src/types.ts:625:26
❯ buildPropertyWithDefaultValue src/index.ts:44:12
42|   defaultValue: any,
43| ) => {
44|   return …
```

fix(codemod): support partial defaultProps

---

apps/cli/src/commands/run.ts
apps/cli/src/fetch-codemod.ts
apps/cli/src/utils/logs.ts

- Allow running `codemod --logs` which opens directory with logs
- Fixes logic for downloading recipe codemods

fix(cli): allow `--logs` usage without codemod name, fix recipe runs

---

apps/cli/Dockerfile
apps/cli/package.json
apps/cli/src/credentials-storage.ts
packages/utilities/src/package-boilerplate.ts

Addresses issue from Community slack.
- Adds shim for keytar for local filesystem-based storaging
- Removes constraint to only warn Linux. This would not print the error on WSL

fix(cli): wsl issue

---

apps/docs/guides/building-codemods/codemod2.mdx

This PR replaces an ambiguous `ast-grep` reference in the Codemod 2.0 page with a more detailed description with links to the `ast-grep` docs.

docs: replace ambiguous ast-grep reference in Codemod 2.0 page

---

apps/cli/package.json
packages/runner/src/source-code.ts

fix issue with building from source code if relative path is used

fix(cli): fix relative path codemod build from source

---

apps/docs/deploying-codemods/workflow-engine.mdx

> Previously, the Asynchronous Context Tracking was leading to a 404 page!

feat(docs): Update Doc Link

---

packages/codemods/typescript/use-template-literals/src/index.ts

refactor: use-template-literals: reuse isStringLiteral

---

packages/codemods/tanStack/codeSplitting/.codemodrc.json
packages/codemods/tanStack/codeSplitting/.gitignore
packages/codemods/tanStack/codeSplitting/LICENSE
packages/codemods/tanStack/codeSplitting/README.md
packages/codemods/tanStack/codeSplitting/package-lock.json
packages/codemods/tanStack/codeSplitting/package.json
packages/codemods/tanStack/codeSplitting/src/index.ts
packages/codemods/tanStack/codeSplitting/tsconfig.json
packages/codemods/tanStack/codeSplitting/vitest.config.ts
pnpm-lock.yaml

> You can find the implementation[ here](https://codemod.com/registry/tanStackRouter-CodeSplitting)

feat(codemod) : TanStack Router Code Splitting

---

apps/backend/src/constants.ts
apps/frontend/app/(website)/studio/features/modGPT/ChatWindow/ModelSelector.tsx
apps/frontend/app/(website)/studio/src/api/sendMessage.ts
apps/modgpt/src/routes/sendChat.ts

Use better models from modgpt.
Currently, we use gpt-4 for all request which is more expensive compared to GPT-4o which has [shown good performance already](https://codemod.com/blog/iterative-ai-system)
We also use use gpt-4 for naming codemods from source code which is overkill, expensive and slows down "Run via CLI" action. I switched it to `4o-mini`

chore(studio): Update GPT models used with ModGPT

---

apps/docs/sharing/publishing-codemods.mdx

This PR adds a section for publishing with the studio publish feature.

docs(publishing-guide): add publish with studio option

---

apps/cli/src/commands/init.ts
apps/cli/src/commands/publish.ts
packages/runner/src/source-code.ts
packages/utilities/src/package-boilerplate.ts
pnpm-lock.yaml

- Fixed issues related to the Codemod CLI by resolving the build failure when using the publish command.
- Removed the automatic installation of dependencies during the init command, ensuring that packages are not installed at initialization.
- Fixed the .gitignore issue in the `package-boilerplate.ts` file.
- Removed the LICENSE file from the list of boilerplate files in `package-boilerplate.ts`.
- Verified that the Codemod CLI build works correctly when using the publish command.
- Ensured no dependencies are installed when the init command is executed.
- Checked that the LICENSE file is no longer part of the boilerplate list in the relevant files.

fix(apps/cli): resolve issues with publish command, init command, and boilerplate files

---

apps/frontend/sanity/schemas/sections/features.ts

Decreases features section minimum allowed items limit so that we can add landing pages with less than 5 items.

fix(frontend): Decrease features section validation limit

---

.changeset/spotty-donuts-tap.md
pnpm-lock.yaml

This PR includes the changes and summary for [PR #1418](https://github.com/codemod-com/codemod/pull/1418). It uses `pnpm changeset` to resolve issues with the `publish` the Codemod CLI from the previous PR.

feat: add changeset for #1418 PR changes

---

apps/frontend/components/templates/Registry/helpers.ts

This PR improves the UI/UX of the registry page by hiding the "example" heading in the `getDescriptionShortText` function. Removing this unnecessary heading results in a cleaner and more streamlined user experience.

fix: hide example heading in markdown purview in registry card

---

.changeset/honest-vans-hope.md
packages/utilities/src/package-boilerplate.ts

This PR modifies the ```README.md``` template generated by the ```codemod init``` command in the CLI. The update ensures that the starter boilerplate now includes the latest format for the ```README.md``` file, providing a more accurate and standardized setup for new projects.
This change improves the quality of the initial project structure created by the CLI but does not affect any functional aspects of the tool itself.
---
- Ran the ```codemod init``` command locally to verify that the updated ```README.md``` template is applied correctly.
- Checked the generated template for consistency with the latest standards.

chore(apps/cli): update README.md template in starter boilerplate for codemod init

---

.changeset/kind-roses-try.md
apps/cli/src/commands/publish.ts

This PR removes the **auto bump version** from the publish step in CLI.  
Versioning will now be handled manually to provide more control over releases.  
- Manually test the CLI in different cases.

chore(apps/cli): remove auto bump version in publish step

---

.changeset/beige-planes-happen.md
packages/codemod-utils/package.json
packages/codemod-utils/tsup.config.ts

This PR adds `tsup` as a build tool and includes CommonJS (`.cjs`) support in **codemod-utils**.  
With this change, the package can now be used with both `import` and `require`, improving compatibility.  
- Built the package using `tsup` and verified that both ESM (`.js`) and CommonJS (`.cjs`) outputs were generated correctly.  
- Tested importing the package in both `import` and `require` environments to ensure compatibility.

feat(packages/codemod-utils): add tsup and CJS for require support in codemod-utils

---

pnpm-lock.yaml

Update `pnpm-lock.yaml` to incorporate tsup and other dependency changes from #1474 . Fixes unit test workflows in CI that install pnpm dependencies with frozen lock files. 
Trivial change.
Unit tests in GHA succeed, in addition to successful `pnpm install --frozen-lockfile` locally.
None.

fix(infra): update pnpm lock, incl deps from #1474

---

apps/frontend/components/global/Navigation/LogoWithContextMenu.tsx

This PR removes the VS Code Extension link from the logo context menu.  
The link was no longer necessary in this location, ensuring a cleaner and more intuitive UI.
- Manually tested the logo context menu to confirm the VS Code Extension link is no longer present.
- Verified that other menu options remain functional.

chore(apps/frontend): remove VS Code Extension link from logo context menu

---

.changeset/ninety-candles-lie.md
apps/cli/package.json
packages/runner/src/runner.ts
packages/runner/src/utils.ts
pnpm-lock.yaml

These changes allow for running certain codemods as child node processes with the ability to resolve node modules both from the codemod cli node_modules and cwd. This is just a hack to unblock nodejs codemods.

feat(runner): add child process support for specific codemod execution

---

.changeset/gold-geckos-tap.md
packages/runner/src/runner.ts

Improvements to node modules resolution:
* [`.changeset/gold-geckos-tap.md`](diffhunk://#diff-7dbe8f0801c9baeaec6ab79108fab58cd6ae03070e82cdb3998e74424a00e049R1-R6): Added a patch change for `@codemod-com/runner` and `codemod` to improve node modules resolution for the node codemod symlinking step.
Codebase simplification:
* [`packages/runner/src/runner.ts`](diffhunk://#diff-5ddcf28ba887dca28edadda699d4e6d7ca9e22bc446d52c957de0b807fb8709fL503-R518): Modified the `Runner` class to use `module.paths.find` for locating the `cli_node_modules` directory and added error handling for cases where the directory is not found.
This pull request includes changes to improve the node modules resolution for the node codemod symlinking step and to handle cases where the `cli_node_modules` directory …

fix: improve node codemod node modules resolution

---

.changeset/pretty-monkeys-watch.md
apps/cli/package.json
packages/runner/src/engines/ast-grep.ts
packages/workflow/src/astGrep/astGrep.ts
pnpm-lock.yaml
pnpm-workspace.yaml

ast-grep offsets are not unicode aware and are just byte offsets. This causes our custom transformer producing broken texts. This PR introduces a fix that utilizes TextEncoder to make the updates unicode-aware.

fix: Fix ast-grep runner when there are special characters

---

apps/docs/building-codemods/package-requirements.mdx
apps/docs/deploying-codemods/cli.mdx
apps/docs/docs.json

Minor update:
- added info about how namespaces work
- added navigation to legacy cli doc

chore(docs): add info about namespaces & update cli nav

---

apps/docs/codemod-registry/introduction.mdx

Fixed a minor typo in the title of [the Codemod Registry page](https://docs.codemod.com/codemod-registry/introduction).
Opened [the Codemod Registry page](https://docs.codemod.com/codemod-registry/introduction).
N/A

style(docs): fix typo in title

---

Cargo.lock
Cargo.toml
crates/codemod-sandbox/Cargo.toml
crates/codemod-sandbox/src/ast_grep/mod.rs
crates/codemod-sandbox/src/ast_grep/native.rs
crates/codemod-sandbox/src/lib.rs
crates/core/Cargo.toml
crates/core/README.md
crates/core/src/engine.rs
crates/core/tests/engine_tests.rs
crates/models/src/step.rs
examples/ast-grep-config.yaml
examples/ast-grep-workflow.yaml
schemas/workflow.json

This PR implements comprehensive AST grep workflow integration
**Technical Implementation:**
- **Native AST Grep Module** (`crates/codemod-sandbox/src/ast_grep/native.rs`): Core implementation with language detection, file traversal, and fix application
- **Engine Integration** (`crates/core/src/engine.rs`): Seamless integration into workflow step execution pipeline
- **Model Updates** (`crates/models/src/step.rs`): Added `UseAstGrep` step action type with comprehensive configuration options
Resolves workflow engine crashes when using AST grep rules with multiple fix directives.
**Unit Tests (All Passing):**
```bash
cargo test ast_grep
```
- ✅ Language detection for 20+ file extensions
- ✅ Pattern matching across JavaScript/TypeScript files  
- ✅ Multiple file processing with glob …

feat: ast-grep step type for workflows

---

apps/docs/building-codemods/codemod2.mdx

Removes reference of deprecated workflow engine api doc.

docs: remove workflow engine api reference

---

.changeset/three-bats-glow.md
apps/backend/src/publishHandler.test.ts
apps/backend/src/publishHandler.ts
apps/backend/src/server.ts
apps/cli/src/commands/publish.ts
apps/cli/src/main.ts
apps/cli/test/credentialsStorage.test.ts
packages/api-types/src/errors.ts

This PR introduces a breaking change by:
- Refactoring deprecated backend endpoints to return a `410 GONE` HTTP error.
- Disabling all old CLI commands except for `codemod run`.
These changes aim to clean up legacy functionality, reduce confusion for users, and encourage the use of supported interfaces only.
- Verified that requests to deprecated endpoints return a `410 GONE` response with the correct message.
- Ran old CLI commands to confirm that only `codemod run` is allowed.

refactor: return 410 GONE for deprecated endpoints and restrict old CLI to only `codemod run`

---

packages/workflow/src/fs/move.ts

Relative paths can also link to hidden directories (e.g. `.nuxt/eslint.config.mjs`). The check for "is it already a relative path" should therefore be for `./` - not just for `.`.
Fixes #1425
Fixes #1247
fixes [#commons/issues/66 ](https://github.com/codemod-com/commons/issues/66)
* Create a plain nuxt project including eslint
* add `  future: {    compatibilityVersion: 4,  },` to the nuxt config
* run codemod `nuxt/4/file-structure` against this
Before / without this PR: 
After: no change to the eslint.config.mjs file

Relative paths can start with a dot for hidden files

---

apps/docs/cli/cli-reference.mdx
apps/docs/cli/workflows.mdx

- CLI Reference: Convert subcommand headings to H4s and switch subcommands' options to Mintlify ResponseFields
- Workflows: Fix Quick Start example to match actual CLI output, validate all workflow examples, and fix missing required fields
- Examples: Ensure all workflow examples pass `npx codemod@next workflow validate `and are syntactically correct

docs: Improve new CLI docs

---

crates/cli/src/commands/jssg/run.rs
crates/cli/src/commands/run.rs
crates/cli/src/commands/workflow/run.rs
crates/cli/src/dirty_git_check.rs
crates/cli/src/main.rs

This PR adds support for detecting a dirty Git working tree before executing codemod using run commands. This feature has been integrated into the following commands:
- `run`
- `jssg/run`
- `workflow/run`
If the repository contains uncommitted changes, a warning will be displayed to inform users before proceeding. This ensures improved awareness and safety during codemod executions.
- Verified that the dirty state check works for all 3 run-related commands.
- Manually tested the behavior with both clean and dirty Git states.
- Confirmed that warnings are shown appropriately and command behavior remains unchanged otherwise.
- Confirmed `--allow-dirty` is working as well

feat(CLI): add git dirty check for `run` commands

---

.github/workflows/cargo-release.yml
Cargo.lock
crates/codemod-sandbox/Cargo.toml
crates/codemod-sandbox/src/sandbox/engine/quickjs_adapters.rs
crates/codemod-sandbox/src/utils/transpiler.rs

- Refactor transpiler to use `swc_ts_fast_strip` for TypeScript stripping.
- Bump `swc_core` to version 33.0
- Add `swc_ts_fast_strip`
- Remove unused packages like `sourcemap` and `ptr_meta`.

feat: switch to swc_ts_fast_strip

---

apps/docs/cli/workflows.mdx
apps/docs/docs.json
apps/docs/migrations.mdx

Update workflow docs & hide opportunity finder.
1. `docs.json`  
• Dropped *Opportunity Finder* and *platform/workflows* from nav.
2. `migrations.mdx`  
• Renamed to **Migration Campaigns**.  
• Inlined old Workflows content (demo + steps + CLI link).  
• Added subtle Opportunity Finder note, enterprise/pro visibility note, and Mintlify callouts.  
• Replaced stray HTML with Markdown.

docs: Deprecate opportunity finder & update workflows docs

---

Cargo.lock
crates/cli/src/commands/jssg/bundle.rs
crates/cli/src/commands/jssg/mod.rs
crates/cli/src/commands/publish.rs
crates/cli/src/main.rs
crates/codemod-sandbox/Cargo.toml
crates/codemod-sandbox/src/utils/bundler/mod.rs
crates/codemod-sandbox/src/utils/bundler/module_analyzer.rs
crates/codemod-sandbox/src/utils/bundler/module_transformer.rs
crates/codemod-sandbox/src/utils/bundler/module_transformer_tests.rs
crates/codemod-sandbox/src/utils/bundler/runtime_commonjs.tpl
crates/codemod-sandbox/src/utils/bundler/runtime_custom.tpl
crates/codemod-sandbox/src/utils/mod.rs

- Introduced a new `bundle` command in the JSSG CLI for bundling JSSG codemods and their dependencies.
- Implemented a bundler utility that processes and bundles JS files, integrating with existing module resolution.
- Refactored existing commands to accommodate the new bundling functionality.
- Auto bundle JSSG codemods on publish

feat(cli): bundle jssg codemods pre-publish

---

crates/codemod-sandbox/src/ast_grep/sg_node.rs
crates/codemod-sandbox/src/ast_grep/types.rs

The type `Position` in @codemod.com/jssg-types differs from what is returned in Range objects in JavaScript.
Looking at the ast-grep Rust implementation, the line is returned as row there. If this change needs to be made in the Rust code rather than in the type definitions, please let me know, I’d be happy to contribute to the Rust code (I tried to run it but had some issues setting up the development environment, so I’ll need some help with it. I can also use this opportunity to document how to setup development environment in the CONTRIBUTING.md).
https://github.com/codemod-com/codemod/blob/6578c1672bde74559c341e8adf89556c7bc464c5/crates/codemod-sandbox/src/ast_grep/sg_node.rs#L154-L165
https://github.com/nodejs/userland-migrations/pull/136

fix(codemod-sandbox): Replace row with line in JsPosition to match the types from @ast-grep/napi

---

crates/cli/src/commands/publish.rs
crates/codemod-sandbox/src/sandbox/errors.rs

Previously, the _bundler errors_ on publish were getting swallowed. We should stop the publish process when jssg entry file cannot be bundled.

fix: prevent publishing codemods when jssg module resolution fails

---

apps/docs/docs.json

[Merging is optional] See if you like how this more than the darker background we currently have. If you like the darker background, we can change the background of the illustration on the intro page to use the same color.
Updates docs background color to brand dark blue

[SAL-286] docs: Update bg color

---

apps/docs/cli/cli-reference.mdx

The line `It’s built for speed and simplicity, making ast-grep codemods a first-class experience.` was duplicated in the doc. This PR removes the duplicate line.

chore(docs): remove duplicated line cli reference

---

README.md
apps/docs/api-reference/transformation/astgrep/reference.mdx
apps/docs/building-codemods/codemod2.mdx
apps/docs/cli/cli-reference.mdx
apps/docs/cli/workflows.mdx
apps/docs/deploying-codemods/cli.mdx
apps/docs/guides/migrations/msw-v1-v2.mdx
apps/docs/guides/migrations/nuxt-3-4.mdx
apps/docs/guides/migrations/react-18-19.mdx
apps/docs/guides/migrations/zod-3-4.mdx
crates/cli/README.md

- deprecates `@next` specifier, making the `@next` CLI the stable version.
- removes remaining mentions of the legacy CLI.

docs: deprecate @next specifier

---

Cargo.lock
crates/cli/src/commands/jssg/run.rs
crates/cli/src/commands/publish.rs
crates/cli/src/commands/run.rs
crates/cli/src/commands/workflow/run.rs
crates/cli/src/main.rs
crates/cli/src/workflow_runner.rs
crates/core/Cargo.toml
crates/core/src/utils.rs
crates/telemetry/Cargo.toml
crates/telemetry/src/send_event.rs
crates/telemetry/src/send_null.rs

This PR adds new PostHog tracking events to improve visibility into usage and add disable analytics argument:
- **jssg** runs local jssg now trigger a PostHog event.
- **workflos** send PostHog events when workflow local run.
- **CLI panics** send PostHog events with details when CLI panicked
- Verified locally that jssg and workflow runs trigger PostHog events.  
- Simulated a CLI panic and confirmed the event was sent.

feat(cli/posthog): add events for jssg local and workflow local runs, and cli panics and add disable analytics feature [CDMD-4429] [CDMD-4423]

---

crates/testing-utils/src/fixtures.rs

In the current implementation, `input_tests` and `expected_tests` are stored in a `Vec`. To compare them, the code loops through `input_tests` and uses the index to fetch the corresponding item from `expected_tests`. The issue is that if `expected_tests` has fewer entries, the comparison ends up mismatching inputs and expected content after some.
Additionally, when using the `--update-snapshot flag`, it overwrites the wrong files.
What I this PR does is replace `Vec` by `HashMap` and use filename as `Key`
This PR also fixes a case where  files created by `--update-snapshot` were sometimes placed in the `./tests` folder instead of in ./tests/expected or `./tests/${test-case}`
---
I don’t have much experience with Rust, so if something can be improved or needs to be refactored, please let …

fix(testing-utils): tests compare against the wrong expected result when there are fewer expected files than input files.

---

crates/cli/src/commands/init.rs
crates/cli/src/templates/codemod.yaml

Add git repository url prompt for init command

feat: add repository choice into init
